const beforeApprovalTemplates=views.templates;
views.templates=async()=>{
 const el=await beforeApprovalTemplates(),[d,categories,products]=await Promise.all([api('/approval-rules'),api('/product-categories'),api('/products')]);
 const own=(kind,id)=>d.rules.find(r=>r.kind===kind&&r.record_id===id),summary=r=>!r?'Chưa thiết lập':`${r.confirmed?'':'Chưa đủ ngưỡng · '}Tiền: ${r.amount===null?'chưa đặt':vnd(r.amount)} · Giảm thêm: ${r.discount===null?'chưa đặt':r.discount+'%'} · ${r.money_scope==='quote'?'Cả báo giá':'Riêng sản phẩm'} · ${r.basis==='gross'?'Trước giảm':'Sau giảm'}`;
 const section=$(`<section class="card approval-settings"><h3>Duyệt báo giá theo sản phẩm / dịch vụ</h3><p class="small">Nhóm: <strong>${esc(d.team_name)}</strong>. Trưởng nhóm thiết lập ngưỡng cho nhóm mình. Sản phẩm chưa có ngưỡng riêng dùng ngưỡng của loại. Vượt một trong hai ngưỡng thì cả báo giá trình giám đốc; bằng ngưỡng vẫn do trưởng nhóm duyệt.</p><p class="small">Báo giá đang chờ duyệt giữ chính sách lúc trình. Trưởng nhóm lập báo giá luôn trình giám đốc. Ngưỡng chung đã cấu hình được chuyển thành mặc định của loại, giữ cách so với cả báo giá. Trưởng nhóm có thể đổi cách tính hoặc đặt ngưỡng riêng.</p>${!d.can_edit?'<p class="hint">Đăng nhập vai trò Trưởng nhóm để thiết lập ngưỡng; admin tiếp tục quản lý danh mục và mẫu.</p>':''}${categories.map((c,index)=>{const r=own('category',c.id);return `<details class="approval-category" ${index===0?'open':''}><summary><strong>${esc(c.name)}</strong> · ${r?.confirmed?'Đã thiết lập':'Cần thiết lập'}</summary><div class="balance"><div><strong>Ngưỡng mặc định của loại</strong><p class="small">${esc(summary(r))}</p></div>${d.can_edit?`<button data-rule-kind="category" data-rule-id="${esc(c.id)}">Thiết lập ngưỡng loại</button>`:''}</div><div class="catalog-table-wrap"><table><thead><tr><th>Sản phẩm / dịch vụ</th><th>Ngưỡng áp dụng</th>${d.can_edit?'<th>Thao tác</th>':''}</tr></thead><tbody>${products.filter(p=>p.family===c.id).map(p=>{const pr=own('product',p.code);return `<tr><td>${esc(p.name)}</td><td><small>${pr?'Thiết lập riêng':'Dùng ngưỡng loại'}</small><p class="small">${esc(summary(pr||r))}</p></td>${d.can_edit?`<td><button data-rule-kind="product" data-rule-id="${esc(p.code)}">${pr?'Sửa ngưỡng riêng':'Thiết lập riêng'}</button>${pr?`<button data-rule-inherit="${esc(p.code)}">Dùng ngưỡng loại</button>`:''}</td>`:''}</tr>`;}).join('')||'<tr><td colspan="3">Chưa có sản phẩm.</td></tr>'}</tbody></table></div></details>`;}).join('')}</section>`);
 el.querySelector('.catalog-section').after(section);
 const jump=$('<button class="major">'+(d.can_edit?'Thiết lập duyệt báo giá':'Xem ngưỡng duyệt')+'</button>');el.querySelector('.hero').append(jump);jump.onclick=()=>{section.scrollIntoView({behavior:'smooth',block:'start'});};
 action(section,'[data-rule-kind]',b=>{const kind=b.dataset.ruleKind,id=b.dataset.ruleId,item=kind==='product'?products.find(p=>p.code===id):categories.find(c=>c.id===id),existing=own(kind,id),base=existing||(kind==='product'?own('category',item.family):null);form('Ngưỡng duyệt — '+item.name,[['amount','Vượt giá trị này cần giám đốc duyệt (VNĐ) *','number',null,base?.amount??''],['discount','Vượt giảm thêm này cần giám đốc duyệt (%) *','number',null,base?.discount??''],['money_scope','Khoản tiền đem so với ngưỡng','select',[['line','Giá trị riêng sản phẩm: đơn giá × số lượng'],['quote','Tổng giá trị cả báo giá']],base?.money_scope||'line'],['basis','Giá trị trước hay sau giảm thêm','select',[['net','Sau giảm thêm'],['gross','Trước giảm thêm']],base?.basis||'net']],async body=>{await api('/approval-rules/'+kind+'/'+encodeURIComponent(id),{method:'PUT',body});toast('Đã lưu ngưỡng duyệt cho nhóm. Báo giá đang chờ duyệt giữ chính sách cũ.');render();});});
 action(section,'[data-rule-inherit]',b=>form('Dùng lại ngưỡng của loại',[['confirm','Xác nhận bỏ ngưỡng riêng; các lần trình duyệt sau dùng ngưỡng của loại','check',null,false]],async body=>{if(!body.confirm)throw Error('Đánh dấu xác nhận trước khi lưu.');await api('/approval-rules/product/'+encodeURIComponent(b.dataset.ruleInherit)+'/inherit',{body:{}});render();}));return el;
};
function approvalBreakdown(route){return route?.checks?.length?`<details><summary>Ngưỡng áp dụng theo từng hạng mục</summary>${route.checks.map(c=>`<p class="small"><strong>${esc(c.name)}</strong><br>${esc(c.source==='product'?'Ngưỡng riêng':'Ngưỡng loại')}: ${vnd(c.amount)} / giảm thêm ${c.discount}%<br>Giá trị so sánh: ${vnd(c.value)} (${c.money_scope==='quote'?'cả báo giá':'riêng sản phẩm'}, ${c.basis==='gross'?'trước giảm':'sau giảm'}) · ${c.overAmount||c.overDiscount?'Vượt ngưỡng → Giám đốc':'Trong ngưỡng'}</p>`).join('')}</details>`:'';}
const beforeApprovalQuote=views.quote;views.quote=async id=>{const el=await beforeApprovalQuote(id),d=await api('/quotes/'+id),r=d.route||(d.quote.policy?JSON.parse(d.quote.policy):null);const info=$( `<section class="card"><h3>Chính sách duyệt ${d.quote.status==='PENDING'?'đã chốt':'theo hạng mục đã lưu'}</h3>${r?.blocked?`<p class="err">${esc(r.blocked)}</p>`:r?`<p>Cấp duyệt: <strong>${r.level==='director'?'Giám đốc':'Trưởng nhóm'}</strong></p>`:'<p>Chính sách sẽ được xác định khi trình duyệt.</p>'}${approvalBreakdown(r)}<p class="small">Sau khi thay hạng mục hoặc chiết khấu, lưu nội dung để kiểm tra lại cấp duyệt.</p></section>`);el.append(info);return el;};
