const catalogStyle=document.createElement('link');catalogStyle.rel='stylesheet';catalogStyle.href='/catalog.css';document.head.append(catalogStyle);
function quoteLogo(value){return typeof value==='string'&&/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/]+=*$/.test(value)?`<img class="company-logo" src="${esc(value)}" alt="Logo công ty">`:'';}
function logoPicker(value='',label='Logo công ty'){
 const el=$(`<div class="logo-picker"><label><span>${esc(label)}</span><input type="file" accept="image/png,image/jpeg,image/webp" aria-label="${esc(label)}"></label><div class="logo-preview"></div><button type="button">Bỏ logo đã chọn</button><p class="small">PNG, JPG hoặc WebP, tối đa 300 KB. Logo xuất hiện trên bản in / PDF báo giá.</p><p role="alert" class="err"></p></div>`);let current=value,loading=false;
 const fill=()=>{el.querySelector('.logo-preview').innerHTML=quoteLogo(current)||'<span class="small">Chưa chọn logo</span>';el.querySelector('button').disabled=!current;};fill();
 el.querySelector('input').onchange=async e=>{const file=e.target.files[0];if(!file)return;loading=true;el.querySelector('[role=alert]').textContent='';try{if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>300*1024)throw Error('Chọn ảnh PNG, JPG hoặc WebP tối đa 300 KB.');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('Không đọc được tệp.'));reader.readAsDataURL(file);});await new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>img.width>4096||img.height>4096?reject(Error('Logo tối đa 4.096 pixel mỗi chiều.')):resolve();img.onerror=()=>reject(Error('Tệp không phải ảnh hợp lệ.'));img.src=data;});current=data;fill();}catch(err){el.querySelector('[role=alert]').textContent=err.message;}finally{loading=false;e.target.value='';}};
 el.querySelector('button').onclick=()=>{current='';fill();};el.value=()=>{if(loading)throw Error('Đang đọc logo, vui lòng chờ một chút.');return current;};return el;
}
const supplyLabels={unknown:'Chưa xác định',self:'Công ty tự cung cấp',partner:'Hợp tác với đối tác',distributor:'Phân phối cho đối tác'};
function supplyText(p){return (supplyLabels[p.supply_type]||supplyLabels.unknown)+(p.partner_name?' · '+p.partner_name:'');}
const oldTemplatesView=views.templates;
views.templates=async()=>{
 const [el,d,products,categories]=await Promise.all([oldTemplatesView(),api('/templates'),api('/products'),api('/product-categories')]),admin=me.role==='admin';
 const categoryName=id=>categories.find(c=>c.id===id)?.name||id;
 el.querySelector('.lead').textContent='1. Tạo loại dịch vụ và đơn giá → 2. Chọn hạng mục cho mẫu → 3. Sales lập báo giá.';
 const catalogue=$(`<section class="card catalog-section"><div class="section-heading"><div><h3>Danh mục sản phẩm / dịch vụ và đơn giá</h3><p class="small">Giá VNĐ chưa thuế. Sửa danh mục áp dụng cho báo giá tạo mới; báo giá đã lập giữ nguyên giá.</p></div>${admin?'<div class="actions"><button id="category-add">+ Loại sản phẩm / dịch vụ</button><button class="major" id="product-add">+ Sản phẩm / dịch vụ</button></div>':''}</div><div class="catalog-categories">${categories.map(c=>`<span class="chip">${esc(c.name)}${admin?` <button data-category="${esc(c.id)}" aria-label="Sửa loại ${esc(c.name)}">Sửa</button>`:''}</span>`).join('')}</div><div class="catalog-filters"><input type="search" aria-label="Tìm sản phẩm dịch vụ" placeholder="Tìm mã hoặc tên sản phẩm / dịch vụ…"><select aria-label="Lọc loại sản phẩm"><option value="">Tất cả loại</option>${categories.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}</select></div><div class="catalog-table-wrap"><table><thead><tr><th>Sản phẩm / dịch vụ</th><th>Loại</th><th>Đơn vị cung cấp</th><th>ĐVT</th><th>Đơn giá / năm đầu</th><th>Gia hạn / năm</th><th>Trạng thái</th>${admin?'<th>Thao tác</th>':''}</tr></thead><tbody></tbody></table></div></section>`);
 el.querySelector('.two').before(catalogue);
 const editProduct=p=>{form(p?'Sửa sản phẩm / dịch vụ':'Thêm sản phẩm / dịch vụ',[
  ...(!p?[['code','Mã sản phẩm * (chữ, số, gạch nối)','text',null,'SP-'+Date.now()]]:[]),['name','Tên sản phẩm / dịch vụ *','text',null,p?.name],['family','Loại sản phẩm / dịch vụ','select',categories.map(c=>[c.id,c.name]),p?.family],['supply_type','Hình thức cung cấp','select',Object.entries(supplyLabels),p?.supply_type||'unknown'],['partner_name','Tên đối tác * (khi hợp tác hoặc phân phối)','text',null,p?.partner_name||''],['unit','Đơn vị tính * (gói, buổi, giờ…)','text',null,p?.unit||'Gói'],['first_year','Đơn giá / năm đầu (VNĐ, chưa thuế) *','number',null,p?.first_year??''],['renewal','Gia hạn / năm (để trống nếu chưa xác định; 0 nếu không thu)','number',null,p?.renewal??''],['description','Giới thiệu / Mô tả riêng (để trống dùng mặc định của loại)','textarea',null,p?.description||''],['terms','Điều kiện thương mại riêng (để trống dùng mặc định của loại)','textarea',null,p?.terms||''],['active','Đang bán — có thể chọn cho báo giá mới','check',null,p?!!p.active:true]
 ],async body=>{await api('/products/'+encodeURIComponent(p?.code||body.code),{method:'PUT',body});toast('Đã lưu danh mục và đơn giá.');render();});const dialog=document.querySelector('dialog:last-of-type'),source=dialog.querySelector('[name=supply_type]'),partner=dialog.querySelector('[name=partner_name]');partner.maxLength=250;const toggle=()=>{const external=['partner','distributor'].includes(source.value);partner.closest('label').hidden=!external;partner.required=external;};source.onchange=toggle;toggle();};
 const fill=()=>{const term=catalogue.querySelector('input').value.trim().toLocaleLowerCase('vi'),family=catalogue.querySelector('select').value;catalogue.querySelector('tbody').innerHTML=products.filter(p=>(!family||p.family===family)&&[p.code,p.name,p.partner_name,supplyLabels[p.supply_type]].join(' ').toLocaleLowerCase('vi').includes(term)).map(p=>`<tr><td><strong>${esc(p.name)}</strong><div class="small">${esc(p.code)}${p.needs_pkg1?' · Cần đã đăng ký Gói 1':''}</div></td><td>${esc(categoryName(p.family))}</td><td><span class="tag ${p.supply_type==='self'?'ok':'quiet'}">${esc(supplyLabels[p.supply_type]||supplyLabels.unknown)}</span>${p.partner_name?`<div class="small">${esc(p.partner_name)}</div>`:''}</td><td>${esc(p.unit)}</td><td>${vnd(p.first_year)}</td><td>${p.renewal===null?'Chưa xác định':vnd(p.renewal)}</td><td>${tag(p.active?'Đang bán':'Ngừng bán')}</td>${admin?`<td><button data-product="${esc(p.code)}">Sửa</button></td>`:''}</tr>`).join('')||'<tr><td colspan="8">Chưa có sản phẩm phù hợp.</td></tr>';action(catalogue,'[data-product]',b=>editProduct(products.find(p=>p.code===b.dataset.product)));};fill();catalogue.querySelector('input').oninput=fill;catalogue.querySelector('select').onchange=fill;
 const editCategory=c=>form(c?'Sửa loại sản phẩm / dịch vụ':'Thêm loại sản phẩm / dịch vụ',[['name','Tên loại *','text',null,c?.name||''],['description','Giới thiệu / Mô tả mặc định','textarea',null,c?.description||''],['terms','Điều kiện thương mại mặc định','textarea',null,c?.terms||'']],async body=>{await api(c?'/product-categories/'+c.id:'/product-categories',{method:c?'PUT':'POST',body:{...body,id:'loai-'+Date.now()}});render();});
 action(catalogue,'#category-add',()=>editCategory());action(catalogue,'[data-category]',b=>editCategory(categories.find(c=>c.id===b.dataset.category)));action(catalogue,'#product-add',()=>editProduct());
 const brandSection=el.querySelector('#brand-name').closest('section');
 if(admin){const picker=logoPicker(d.brand.logo||'');brandSection.querySelector('#brand').before(picker);action(brandSection,'#brand',async()=>{const body={logo:picker.value()};for(const key of ['name','short','address','contact','color'])body[key]=brandSection.querySelector('#brand-'+key).value;await api('/brand',{method:'PUT',body});toast('Đã lưu nhận diện và logo công ty.');render();});}
 else brandSection.insertAdjacentHTML('beforeend',quoteLogo(d.brand.logo));
 function editTemplate(t){
  const dialog=$(`<dialog class="catalog-template-dialog"><form><h2>${t?'Sửa mẫu báo giá':'Tạo mẫu báo giá'}</h2><label>Tên mẫu *<input name="name" required value="${esc(t?.name||'')}"></label><label>Loại sản phẩm / dịch vụ<select name="family" ${t?'disabled':''}>${categories.map(c=>`<option value="${esc(c.id)}" ${(t?.family||categories[0]?.id)===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><h3>Hạng mục sales được chọn trong mẫu</h3><p class="small">Chọn từ danh mục đơn giá bên trên. Sales chọn hạng mục và số lượng khi lập báo giá. Mỗi hạng mục mang theo mô tả và điều kiện thương mại riêng.</p><div class="template-product-options"></div><p class="hint">Mô tả và điều kiện thương mại lấy từ từng sản phẩm được chọn; nếu để trống sẽ dùng nội dung mặc định của loại. Chỉnh nội dung này trong danh mục bên trên.</p><div class="template-logo-slot"></div><p class="small">Nếu không chọn logo riêng, mẫu sử dụng logo công ty đã lưu ở Nhận diện công ty. Logo của bản đã duyệt được giữ nguyên.</p><div role="alert" class="err"></div><div class="actions"><button type="submit" class="major">Lưu mẫu</button><button type="button" id="cancel-template">Hủy</button></div></form></dialog>`);
  const picker=logoPicker(t?.logo||'','Logo riêng cho mẫu (không bắt buộc)');dialog.querySelector('.template-logo-slot').append(picker);
  const chosen=t?(t.product_codes===null?products.filter(p=>p.family===t.family).map(p=>p.code):JSON.parse(t.product_codes)):[];
  const fillItems=()=>{const family=dialog.querySelector('[name=family]').value;dialog.querySelector('.template-product-options').innerHTML=products.filter(p=>p.family===family).map(p=>`<label class="template-product"><input type="checkbox" data-template-product="${esc(p.code)}" ${chosen.includes(p.code)?'checked':''}><span>${esc(p.name)}<small>${vnd(p.first_year)} / ${esc(p.unit)} · ${esc(supplyText(p))}${p.active?'':' · Đã ngừng bán (không đưa vào báo giá mới)'}</small></span></label>`).join('')||'<p class="hint">Loại này chưa có sản phẩm. Hãy tạo sản phẩm và đơn giá ở danh mục trước.</p>';};fillItems();dialog.querySelector('[name=family]').onchange=fillItems;
  dialog.querySelector('#cancel-template').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();
  dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();const button=dialog.querySelector('[type=submit]');button.disabled=true;try{const body={logo:picker.value(),product_codes:[...dialog.querySelectorAll('[data-template-product]:checked')].map(i=>i.dataset.templateProduct)};for(const key of ['name','family'])body[key]=dialog.querySelector('[name='+key+']').value;await api('/templates/'+(t?.id||'mau-'+Date.now()),{method:'PUT',body});dialog.close();toast('Đã lưu mẫu và danh sách hạng mục.');render();}catch(err){dialog.querySelector('form>[role=alert]').textContent=err.message;}finally{button.disabled=false;}};
  document.body.append(dialog);dialog.showModal();
 }
 action(el,'#new',()=>editTemplate());action(el,'[data-template]',b=>editTemplate(d.templates.find(t=>t.id===b.dataset.template)));
 for(const block of el.querySelectorAll('[data-template]')){const t=d.templates.find(t=>t.id===block.dataset.template),codes=t.product_codes===null?null:JSON.parse(t.product_codes),items=products.filter(p=>p.family===t.family&&(codes===null||codes.includes(p.code))&&p.active);block.before($(`<p class="small"><strong>${items.length} hạng mục đang bán</strong> · ${esc(categoryName(t.family))}<br>${items.map(p=>esc(p.name)).join(' · ')||'Chưa có hạng mục; cần bổ sung trước khi sales sử dụng.'}</p>`));}
 return el;
};

function serviceContent(items,termsOnly=false){
 if(!items.length)return '';
 return '<div class="service-content"><h3>'+ (termsOnly?'Điều kiện thương mại theo sản phẩm / dịch vụ':'Mô tả & điều kiện theo hạng mục đã chọn')+'</h3>'+items.map(i=>'<div class="service-content-item"><h4>'+esc(i.name)+'</h4>'+(!termsOnly?'<p class="small preserve">'+esc(i.description||'Chưa khai báo mô tả.')+'</p>':'')+'<p class="preserve">'+esc(i.terms||'Chưa khai báo điều kiện thương mại.')+'</p></div>').join('')+'</div>';
}
