const channelStateLabels={DRAFT:'Chưa đủ cấu hình',CONFIGURED:'Đã lưu · chưa kiểm tra',VERIFIED:'Đã xác minh tài khoản API',ERROR:'Cần kiểm tra lại',PAUSED:'Tạm dừng cấu hình',ARCHIVED:'Đã lưu trữ'};
const channelKindLabels={messenger:'Messenger',whatsapp:'WhatsApp',viber:'Viber',voice:'Thoại',other:'Kênh khác'};
const channelHistoryLabels={create:'Thêm kênh',edit:'Sửa cấu hình',check_ok:'Xác minh API thành công',check_failed:'Kiểm tra API chưa thành công',pause:'Tạm dừng cấu hình',resume:'Tiếp tục cấu hình',archive:'Lưu trữ',restore:'Khôi phục'};
const beforeManagedChannels=views.channels;
views.channels=async()=>{
 const [el,d]=await Promise.all([beforeManagedChannels(),api('/channel-connections')]),admin=me.role==='admin'&&me.admin_level!=='subadmin';
 const heading=el.querySelector('.page-heading');heading.querySelector('p').textContent='Quản lý các tài khoản liên lạc, cấu hình API và theo dõi trạng thái thực tế.';
 if(admin){const add=$('<button class="major">+ Thêm kênh kết nối</button>');heading.append(add);add.onclick=()=>editChannelConnection(null,d);}
 const section=$(`<section class="card managed-channels"><div class="section-heading"><div><h3>Các kênh bổ sung</h3><p class="small">Messenger, WhatsApp, Viber, Thoại và API khác. Có thể thêm nhiều cấu hình, đặt tên và chọn nhóm phụ trách.</p></div>${admin?'<button data-channel-archives>Đã lưu trữ / Khôi phục</button>':''}</div><p class="hint">Các kênh dưới đây hiện hỗ trợ lưu cấu hình và kiểm tra tài khoản API. Chưa nhận/gửi tin hoặc gọi điện trong CRM. Xác minh API thành công chưa có nghĩa là đã kết nối hộp thư.</p><div class="channel-grid">${d.channels.map(c=>`<section class="card"><span class="tag ${c.state==='VERIFIED'?'ok':c.state==='ERROR'?'bad':'quiet'}">${esc(channelStateLabels[c.state])}</span><h3>${esc(c.name)}</h3><p>${esc(channelKindLabels[c.kind])} · ${esc(c.provider_name)}</p><p class="small">Nhóm phụ trách: ${esc(c.team_name)}</p>${c.account?`<p>API xác minh: <strong>${esc(c.account.account_name||c.account.account_id)}</strong>${c.account.phone_number?' · '+esc(c.account.phone_number):''}</p>`:''}<p class="small">${c.verified_at?'Đã kiểm tra: '+dt(c.verified_at):'Chưa có xác minh API còn hiệu lực.'}</p>${c.missing?.length?`<p class="small">Còn thiếu: ${c.missing.map(esc).join(', ')}</p>`:''}${c.issue?`<p class="err">${esc(c.issue)}</p>`:''}<p class="small">Nhận/gửi trong CRM: chưa triển khai.</p>${admin?`<div class="actions"><button data-channel-edit="${c.id}">Cấu hình kết nối</button><button data-channel-check="${c.id}" ${!c.can_check||c.state==='PAUSED'||c.missing.length?'disabled':''}>Kiểm tra API</button><button data-channel-state="${c.id}" data-next="${c.state==='PAUSED'?'resume':'pause'}">${c.state==='PAUSED'?'Tiếp tục cấu hình':'Tạm dừng'}</button><button data-channel-history="${c.id}">Lịch sử</button><button data-channel-archive="${c.id}">Lưu trữ</button></div>`:'<p class="small">Admin quản lý thông tin API.</p>'}</section>`).join('')||'<p>Chưa thêm kênh. Admin bấm “+ Thêm kênh kết nối” để bắt đầu.</p>'}</div></section>`);
 heading.after(section);
 action(section,'[data-channel-edit]',async b=>editChannelConnection(await api('/channel-connections/'+b.dataset.channelEdit),d));
 action(section,'[data-channel-check]',async b=>{b.disabled=true;b.textContent='Đang kiểm tra…';try{const r=await api('/channel-connections/'+b.dataset.channelCheck+'/check',{body:{}});toast(r.note);}catch(e){toast(e.message);}finally{render();}});
 action(section,'[data-channel-state]',async b=>{await api('/channel-connections/'+b.dataset.channelState+'/state',{body:{action:b.dataset.next}});render();});
 action(section,'[data-channel-archive]',b=>form('Lưu trữ kênh kết nối',[['reason','Lý do * — có thể khôi phục sau','textarea']],async body=>{await api('/channel-connections/'+b.dataset.channelArchive+'/state',{body:{...body,action:'archive'}});render();}));
 action(section,'[data-channel-archives]',async()=>{const list=(await api('/channel-connections?archived=1')).channels,dialog=$(`<dialog class="catalog-template-dialog"><h2>Kênh đã lưu trữ</h2>${list.map(c=>`<div class="balance"><div><strong>${esc(c.name)}</strong><p class="small">${esc(c.archive_reason)} · ${dt(c.archived_at)}</p></div><button data-channel-restore="${c.id}">Khôi phục</button></div>`).join('')||'<p>Chưa có kênh lưu trữ.</p>'}<p class="small">Khôi phục giữ kênh tạm dừng. Tiếp tục cấu hình và kiểm tra lại khi cần.</p><button data-close>Đóng</button></dialog>`);document.body.append(dialog);dialog.showModal();dialog.onclose=()=>dialog.remove();action(dialog,'[data-close]',()=>dialog.close());action(dialog,'[data-channel-restore]',async b=>{await api('/channel-connections/'+b.dataset.channelRestore+'/state',{body:{action:'restore'}});dialog.close();render();});});
 action(section,'[data-channel-history]',async b=>{const c=await api('/channel-connections/'+b.dataset.channelHistory),dialog=$(`<dialog class="catalog-template-dialog"><h2>Lịch sử — ${esc(c.name)}</h2>${c.history.map(h=>`<p><strong>${esc(channelHistoryLabels[h.action]||h.action)}</strong><br><span class="small">${esc(h.user_name)} · ${dt(h.at)}</span></p>`).join('')}<button data-close>Đóng</button></dialog>`);document.body.append(dialog);dialog.showModal();dialog.onclose=()=>dialog.remove();action(dialog,'[data-close]',()=>dialog.close());});return el;
};
function editChannelConnection(c,d){
 const dialog=$(`<dialog class="catalog-template-dialog"><form><h2>${c?'Cấu hình kết nối — '+esc(c.name):'Thêm kênh kết nối'}</h2><label>Loại kênh / nhà cung cấp<select name="provider" ${c?'disabled':''}>${!c?'<option value="">Chọn loại kênh…</option><option value="zalo_oa">Zalo OA — cấu hình hiện có</option>':''}${d.providers.map(p=>`<option value="${p.id}" ${c?.provider===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label><div class="channel-config-fields"></div><p role="alert" class="err"></p><div class="actions"><button type="submit" class="major" data-save-channel>Lưu cấu hình</button><button type="button" data-cancel>Đóng</button></div></form></dialog>`);
 const formEl=dialog.querySelector('form'),select=formEl.elements.provider;
 const fields=()=>{const p=d.providers.find(p=>p.id===select.value),wrap=dialog.querySelector('.channel-config-fields');formEl.querySelector('[data-save-channel]').disabled=!p;if(select.value==='zalo_oa'){wrap.innerHTML='<p>Bản hiện tại kết nối một Zalo OA. Mở cấu hình OA đang có để tiếp tục.</p><button type="button" data-go-oa>Mở cấu hình Zalo OA</button>';wrap.querySelector('button').onclick=()=>{dialog.close();go('#/zalo');};return;}if(!p){wrap.innerHTML='<p>Chọn loại kênh để hiển thị đúng các trường API cần nhập.</p>';return;}
  wrap.innerHTML=`<p class="hint">${esc(p.note)}</p><label>Tên kênh *<input name="connection_name" required maxlength="150" placeholder="Ví dụ: Messenger iViTech" value="${esc(c?.name||'')}"></label><label>Nhóm phụ trách<select name="team_id" required>${d.teams.map(t=>`<option value="${t.id}" ${t.id===c?.team_id?'selected':''}>${esc(t.name)}</option>`).join('')}</select></label>${p.endpoint?`<p class="small">API chính thức: ${esc(p.endpoint)}</p>`:''}<h3>Thông tin kết nối</h3><p class="small">Có thể lưu trước khi nhập đủ. Các mục có dấu * cần để ${p.check?'kiểm tra tài khoản API':'hoàn thiện cấu hình'}. Mã bí mật chỉ nhập tại đây, không gửi qua chat.</p>${p.fields.map(f=>`<label>${esc(f.label)}${f.required?' *':''}${f.choices?`<select name="cfg-${f.key}"><option value="">Chưa xác định</option>${f.choices.map(([value,label])=>`<option value="${esc(value)}" ${c?.config[f.key]===value?'selected':''}>${esc(label)}</option>`).join('')}</select>`:`<input name="cfg-${f.key}" type="${f.secret?'password':f.format==='url'?'url':'text'}" autocomplete="off" maxlength="${f.secret?8192:1000}" value="${f.secret?'':esc(c?.config[f.key]||'')}" placeholder="${f.secret?(c?.has_secrets[f.key]?'Đã lưu mã hóa · để trống để giữ nguyên':'Chưa nhập'):''}">`}</label>${f.secret&&c?.has_secrets[f.key]?`<label class="template-product"><input type="checkbox" data-clear-secret="${f.key}"><span>Xóa mã ${esc(f.label)} đã lưu</span></label>`:''}`).join('')}<p class="small">Lưu thay đổi sẽ yêu cầu kiểm tra API lại. Chưa có đường nhận tin cho các kênh mới; chưa cần đăng ký webhook về localhost.</p>${p.guide?`<p><a href="${esc(p.guide)}" target="_blank" rel="noreferrer">Tài liệu của nhà cung cấp →</a></p>`:''}`;
 };fields();select.onchange=fields;
 formEl.onsubmit=async e=>{e.preventDefault();const button=formEl.querySelector('[data-save-channel]');button.disabled=true;const alert=formEl.querySelector('[role=alert]');alert.textContent='';try{const p=d.providers.find(p=>p.id===select.value);if(!p)throw Error('Chọn nhà cung cấp.');const config=Object.fromEntries(p.fields.map(f=>[f.key,formEl.elements['cfg-'+f.key].value])),body={name:formEl.elements.connection_name.value,provider:p.id,team_id:Number(formEl.elements.team_id.value),revision:c?.revision,config,clear_secrets:[...formEl.querySelectorAll('[data-clear-secret]:checked')].map(el=>el.dataset.clearSecret)};await api('/channel-connections'+(c?'/'+c.id:''),{method:c?'PUT':'POST',body});dialog.close();toast('Đã lưu cấu hình kênh. Nhận/gửi chưa được bật.');render();}catch(e){alert.textContent=e.message;}finally{button.disabled=false;}};
 dialog.querySelector('[data-cancel]').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();document.body.append(dialog);dialog.showModal();
}
