// Customer workspace; navigation menus remain team-wide views of the same data.
// Shared planning and journey components are defined below this profile view.
const previous360Customer=views.customer;
const profile360Key=id=>'customer360:'+String(me.company?.id||me.company?.code||'ivitech')+':'+me.id+':'+id;
const profile360Tabs=[['overview','Tiến trình khách hàng'],['info','Thông tin & Người liên hệ'],['chat','Trao đổi đa kênh'],['tasks','Kế hoạch tiếp xúc'],['sales','Cơ hội & Báo giá'],['deals','Hợp đồng & Thanh toán'],['notes','Ghi chú & Tài liệu']];
views.customer=async id=>{
 sessionStorage.setItem(profile360Key('journey-selection'),String(id));
 await loadPipelineStages();let data=await api('/customers/'+id+'/360');
 let state;try{state=JSON.parse(sessionStorage.getItem(profile360Key(id))||'{}');}catch{state={};}
 state={tab:'overview',person:'',opportunity:'',type:'',from:'',to:'',scroll:0,...state};
 const save=()=>sessionStorage.setItem(profile360Key(id),JSON.stringify(state));
 const root=$('<div class="customer360"></div>');let generation=0;
 const personName=id=>data.contacts.find(p=>p.id===Number(id))?.full_name;
 const oppName=id=>data.opportunities.find(o=>o.id===Number(id))?.title;
 const match=r=>(!state.person||String(r.contact_id)===state.person)&&(!state.opportunity||String(r.opp_id)===state.opportunity);
 const contextFields=(withOpp=true)=>[
  ['contact_id','Người liên hệ thuộc tổ chức','select',[['','Toàn đơn vị / chưa chọn đầu mối'],...data.contacts.map(p=>[p.id,p.full_name])],state.person],
  ...(withOpp?[['opp_id','Cơ hội liên quan','select',[['','Chưa gắn cơ hội'],...data.opportunities.map(o=>[o.id,o.title])],state.opportunity]]:[])
 ];
 const contextLabel=r=>`<small>${esc(data.customer.name)}${r.contact_id?' · '+esc(personName(r.contact_id)||''):''}${r.opp_id?' · '+esc(oppName(r.opp_id)||''):''}</small>`;
 async function refresh(){const y=window.scrollY;data=await api('/customers/'+id+'/360');await paint();window.scrollTo(0,y);}
 function taskForm(kind='Công việc',seed=''){
  return planTask(data.customer,null,refresh,{kind,title:seed,contact_id:state.person,opp_id:state.opportunity});
 }
 function interaction(){form('Ghi nhận trao đổi · '+data.customer.name,[['kind','Loại trao đổi','select',['Cuộc gọi','Cuộc gặp','Trao đổi','Tóm tắt hội thoại'].map(x=>[x,x])],...contextFields(),['body','Nội dung trao đổi *','textarea'],['outcome','Kết quả *','textarea'],['next','Tiếp tục tạo bước tiếp theo sau khi lưu','check']],async body=>{await api('/customers/'+id+'/interactions',{body});state.person=String(body.contact_id||'');state.opportunity=String(body.opp_id||'');save();await refresh();if(body.next)setTimeout(()=>taskForm('Công việc',body.outcome),0);});}
 function opportunity(){form('Tạo cơ hội · '+data.customer.name,[['title','Tên cơ hội *'],...contextFields(false),['est_value','Giá trị dự kiến (VNĐ)','number',null,0],['expected_close','Ngày chốt dự kiến','date']],async body=>{const r=await api('/opportunities',{body:{...body,customer_id:Number(id)}});state.opportunity=String(r.id);save();await refresh();toast('Đã tạo cơ hội, giữ nguyên hồ sơ đang làm việc.');});}
 function rememberLink(a){state.scroll=window.scrollY;save();sessionStorage.setItem('customer360:return',JSON.stringify({id:Number(id),name:data.customer.name,destination:a.getAttribute('href'),key:profile360Key(id)}));}
 function wireLinks(el){el.querySelectorAll('a[href^="#/"]').forEach(a=>a.addEventListener('click',()=>rememberLink(a)));}
 async function paint(){
  const version=++generation,c=data.customer,write=data.capabilities.write;
  if(state.person&&!data.contacts.some(p=>String(p.id)===state.person))state.person='';
  if(state.opportunity&&!data.opportunities.some(o=>String(o.id)===state.opportunity))state.opportunity='';
  const selected=data.opportunities.find(o=>String(o.id)===state.opportunity),work=data.tasks.filter(match),open=work.filter(t=>t.status!=='COMPLETED').sort((a,b)=>(Date.parse(a.due_at)||Infinity)-(Date.parse(b.due_at)||Infinity)),next=open[0];
  const events=data.events.filter(e=>(!state.person||String(e.contact_id)===state.person)&&(!state.opportunity||String(e.opp_id)===state.opportunity));
  const recent=events[0],overdue=open.filter(late).length;
  root.innerHTML=`<section class="card c360-header"><div class="section-heading"><div><div class="eyebrow">HỒ SƠ KHÁCH HÀNG 360°</div><h2>${esc(c.name)}</h2><p>${esc(c.kind==='org'?c.org_type||'Tổ chức':'Khách hàng cá nhân')} · ${c.archived_at?'Đã xóa / lưu trữ':c.do_not_contact?'Không liên hệ':c.needs_followup?'Cần tiếp tục chăm sóc':'Đã xử lý nhu cầu hiện tại'}</p></div><div class="actions"><button data-refresh>Làm mới</button>${write?'<button data-edit>Sửa hồ sơ</button><button data-delete>Xóa khách hàng</button>':'<button data-restore>Khôi phục khách hàng</button>'}</div></div><div class="c360-meta"><span>Phụ trách: <strong>${esc(c.owner_name||'Chưa phân công')}</strong><small>${esc(c.team_name)}</small></span><span>Liên lạc: <strong>${esc(c.phone||'Chưa có số điện thoại')}</strong><small>${esc(c.email||'Chưa có email')}</small></span><span>Dịch vụ quan tâm: <strong>${esc(c.interest||'Chưa ghi nhận')}</strong></span><span>Tương tác gần nhất: <strong>${data.last_interaction?dt(data.last_interaction):'Chưa ghi nhận'}</strong></span></div><p class="small">Kênh được phép: ${data.channels.map(ch=>esc(ch.key==='oa'?'Zalo OA':ch.key==='personal'?'Zalo cá nhân':ch.key)+(ch.permission==='read'?' (chỉ xem)':'')).join(' · ')||'Chưa được phân kênh'} · ${overdue} việc quá hạn trong phạm vi đang chọn</p>${write?'<div class="actions"><button class="major" data-interaction>Ghi nhận trao đổi</button><button data-task>Tạo công việc</button><button data-meeting>Đặt lịch hẹn</button><button data-chat>Mở hội thoại</button><button data-opportunity>Tạo cơ hội</button></div>':''}</section>
  <section class="card c360-progress"><div class="section-heading"><h3>Tiến trình & việc tiếp theo</h3><div class="c360-context"><label>Đầu mối<select data-person>${options([['','Toàn đơn vị'],...data.contacts.map(p=>[p.id,p.full_name])],state.person)}</select></label><label>Tiến trình cơ hội<select data-opportunity-select>${options([['','Tất cả cơ hội'],...data.opportunities.map(o=>[o.id,o.title])],state.opportunity)}</select></label></div></div><div class="c360-steps"><article><small>ĐANG Ở ĐÂU</small><h4>${selected?'Tiến trình cơ hội: '+esc(selected.title):data.opportunities.length+' cơ hội riêng biệt'}</h4>${selected?tag(selected.stage):'<p>Chọn một cơ hội để theo dõi giai đoạn.</p>'}</article><article><small>ĐÃ THỰC HIỆN</small><h4>${esc(recent?.id?.startsWith('work:')?taskHistoryText(recent.title):recent?.title||'Chưa có hoạt động trong phạm vi chọn')}</h4>${recent?'<p>'+dt(recent.at)+'</p>':''}</article><article><small>VIỆC TIẾP THEO</small><h4>${esc(next?.title||'Chưa xác định bước tiếp theo')}</h4>${next?`<p>${esc(next.assignee_name||'Chưa phân công')} · ${esc(dueText(next.due_at))}</p><button data-open-task="${next.id}">Mở công việc</button>`:write?'<button data-task>Tạo công việc</button>':''}</article><article><small>CẦN CHÚ Ý</small><p>${overdue?overdue+' việc quá hạn. ':''}${!c.owner_id?'Khách chưa được phân công. ':''}${open.some(t=>!t.due_at)?'Có việc chưa đặt hạn. ':''}${!next?'Chưa có bước tiếp theo. ':''}${next&&!overdue&&c.owner_id&&!open.some(t=>!t.due_at)?'Chưa có cảnh báo trong phạm vi chọn.':''}</p></article></div></section>
  <div class="c360-tabs" role="tablist" aria-label="Nội dung hồ sơ 360">${profile360Tabs.map(([k,label])=>`<button role="tab" data-360-tab="${k}" aria-selected="${k===state.tab}" class="${k===state.tab?'selected':''}">${label}</button>`).join('')}</div><section class="card c360-content" role="tabpanel"></section>`;
  action(root,'[data-refresh]',refresh);action(root,'[data-edit]',()=>editDirectoryCustomer(id,refresh));action(root,'[data-delete]',()=>deleteDirectoryCustomer(c,()=>go('#/customers')));action(root,'[data-restore]',async()=>{await api('/lifecycle/customers/'+id+'/restore',{body:{}});await refresh();});
  action(root,'[data-task]',()=>taskForm());action(root,'[data-meeting]',()=>taskForm('Cuộc họp'));action(root,'[data-interaction]',interaction);action(root,'[data-opportunity]',opportunity);action(root,'[data-chat]',()=>selectTab('chat'));
  action(root,'[data-open-task]',b=>openContactPlan(data.tasks.find(t=>String(t.id)===b.dataset.openTask),refresh));
  root.querySelector('[data-person]').onchange=e=>{state.person=e.target.value;save();paint();};root.querySelector('[data-opportunity-select]').onchange=e=>{state.opportunity=e.target.value;save();paint();};
  action(root,'[data-360-tab]',b=>selectTab(b.dataset['360Tab']));
  const box=root.querySelector('.c360-content');
  if(state.tab==='overview'||state.tab==='tasks'){
   root.querySelector('.c360-progress').remove();
   root.querySelector('.c360-header').replaceWith(customerWorkHeader(c,state.tab));
   root.querySelector('[data-profile]').onclick=e=>{e.preventDefault();selectTab('info');};
   if(state.tab==='overview')await renderJourneyPanel(box,data,state,refresh,()=>{save();paint();});
   else await renderPlanningPanel(box,data.tasks,data.customer,state,refresh);
  }else if(state.tab==='info'){
   const old=await previous360Customer(id);if(version!==generation)return;
   if(c.kind==='org'){const tabs=old.querySelector('.profile-tabs');tabs.querySelectorAll('[data-tab]').forEach(b=>b.remove());box.append(tabs,old.querySelector('.profile-tab-content'));const child=old.querySelector('.page-heading .actions .major');if(child)box.prepend(child);}
   else box.innerHTML=`<h3>Thông tin cá nhân</h3><p>${esc(c.name)} · ${esc(c.phone||'Chưa có điện thoại')} · ${esc(c.email||'Chưa có email')}</p><p>Đây là khách hàng cá nhân độc lập. Chưa có quan hệ doanh nghiệp được ghi nhận.</p>`;
  }else if(state.tab==='sales'){
   const os=data.opportunities.filter(o=>(!state.person||String(o.contact_id)===state.person)&&(!state.opportunity||String(o.id)===state.opportunity)),qs=data.quotes.filter(q=>(!state.opportunity||String(q.opp_id)===state.opportunity)&&(!state.person||os.some(o=>o.id===q.opp_id)));
   box.innerHTML=`<div class="section-heading"><h3>Cơ hội bán hàng (${os.length})</h3>${write?'<button data-new-opp>+ Tạo cơ hội</button>':''}</div>${os.map(o=>`<article class="c360-opportunity"><div class="section-heading"><a href="#/opportunity/${o.id}"><strong>${esc(o.title)}</strong></a>${tag(o.stage)}</div>${contextLabel({...o,opp_id:o.id})}<p>${vnd(o.est_value)} · ${esc(o.owner_name||'Chưa phân công')}</p>${write?`<div class="actions"><button data-stage="${o.id}">Đổi giai đoạn</button><button data-edit-opp="${o.id}">Sửa cơ hội</button><button data-quote="${o.id}">Tạo báo giá cho cơ hội</button></div>`:''}</article>`).join('')||empty('Chưa có cơ hội phù hợp')}<div class="section-heading"><h3>Báo giá (${qs.length})</h3>${write?'<button data-general-quote>Tạo báo giá</button>':''}</div>${qs.map(q=>`<a class="activity-row" href="#/quote/${q.id}"><strong>${esc(q.code)} · v${q.version}</strong>${tag(q.status)}<small>${esc(oppName(q.opp_id)||'Chưa gắn cơ hội')}</small></a>`).join('')||empty('Chưa có báo giá phù hợp')}`;
   action(box,'[data-new-opp]',opportunity);action(box,'[data-stage]',b=>{const o=os.find(o=>String(o.id)===b.dataset.stage);form('Giai đoạn · '+o.title,[['to','Giai đoạn','select',STAGES.map(v=>[v,v]),o.stage]],async v=>{setTimeout(()=>changeOpportunityStage(o,v.to,refresh),0);});});
   action(box,'[data-edit-opp]',b=>{const o=os.find(o=>String(o.id)===b.dataset.editOpp);form('Sửa cơ hội',[['title','Tên cơ hội *','text',null,o.title],['est_value','Giá trị dự kiến','number',null,o.est_value],['expected_close','Ngày dự kiến chốt','date',null,o.expected_close||'']],async body=>{await api('/opportunities/'+o.id,{method:'PUT',body});await refresh();});});
   const quote=o=>{sessionStorage.setItem('customer360:return',JSON.stringify({id:Number(id),name:c.name,key:profile360Key(id),destination:'#/quote/'}));save();newQuote(c,o);};action(box,'[data-quote]',b=>quote(os.find(o=>String(o.id)===b.dataset.quote)));action(box,'[data-general-quote]',()=>quote(selected||null));
  }else if(state.tab==='chat'){
   box.innerHTML=`<h3>Hội thoại được phép xem (${data.conversations.length})</h3><p class="small">Chỉ hội thoại gắn trực tiếp với khách này và kênh được phân quyền. Chưa có liên kết hội thoại theo từng đầu mối hoặc cơ hội.</p>${data.conversations.map(v=>`<article class="c360-opportunity"><strong>${esc(v.channel)}</strong><p>${esc(v.last_body||'Chưa có tin nhắn')}</p><small>${dt(v.last_at)}</small><div class="actions"><button data-read-chat="${v.id}">Xem tin nhắn tại đây</button><a href="#/conversation/${v.id}">Mở hội thoại để xử lý →</a></div><div data-messages="${v.id}"></div></article>`).join('')||empty('Chưa có hội thoại được phép xem')}`;
   action(box,'[data-read-chat]',async b=>{const v=await api('/conversations/'+b.dataset.readChat);const target=box.querySelector('[data-messages="'+b.dataset.readChat+'"]');target.innerHTML=v.messages.map(m=>`<div class="c360-message"><small>${esc(m.user_name||({customer:'Khách hàng',bot:'Bot',system:'Hệ thống',agent:'Nhân viên'}[m.sender])||m.sender)} · ${dt(m.at)}</small><p class="preserve">${esc(m.body)}</p></div>`).join('')||empty('Chưa có tin nhắn');});
   if(write&&data.channels.some(ch=>['oa','personal'].includes(ch.key)&&ch.permission==='send')){const b=$('<button>+ Mở hội thoại thử mới</button>');box.append(b);b.onclick=()=>form('Hội thoại mô phỏng · '+c.name,[['channel','Kênh được phép gửi','select',data.channels.filter(ch=>['oa','personal'].includes(ch.key)&&ch.permission==='send').map(ch=>[ch.key,ch.key==='oa'?'Zalo OA (mô phỏng)':'Zalo cá nhân (mô phỏng)'])]],async body=>{await api('/conversations',{body:{...body,customer_id:c.id}});await refresh();});}
  }else if(state.tab==='deals')box.innerHTML=`<h3>Hợp đồng & Thanh toán</h3><div class="notice">Chưa triển khai module lưu hợp đồng, ghi nhận thanh toán và theo dõi công nợ. Chưa có dữ liệu thanh toán để hiển thị.</div><h4>Xác nhận đã ký từ cơ hội</h4>${data.opportunities.filter(o=>o.contract_signed&&(!state.opportunity||String(o.id)===state.opportunity)&&(!state.person||String(o.contact_id)===state.person)).map(o=>`<a class="activity-row" href="#/opportunity/${o.id}"><strong>${esc(o.title)}</strong><span>${vnd(o.final_value)} · ${dt(o.closed_at)}</span></a>`).join('')||empty('Chưa ghi nhận cơ hội đã ký')}<p class="small">Xác nhận hai bên đã ký không phải hồ sơ hợp đồng hoặc bằng chứng thanh toán. Không đánh dấu toàn bộ khách hàng hoàn thành.</p>`;
  else {
   box.innerHTML=`<div class="section-heading"><h3>Ghi chú của khách hàng</h3>${write?'<button data-add-note>+ Ghi chú</button>':''}</div><p class="small">Ghi chú chung của hồ sơ, chưa phân loại theo đầu mối/cơ hội.</p>${data.notes.map(n=>`<article class="c360-opportunity"><p class="preserve">${esc(n.body)}</p><small>${esc(n.user_name||'')} · ${dt(n.at)}</small>${write?`<button data-edit-note="${n.id}">Sửa ghi chú</button>`:''}</article>`).join('')||empty('Chưa có ghi chú')}<h4>Tài liệu</h4><p>Chưa triển khai tải tệp đính kèm hồ sơ. Các báo giá đã có nằm ở tab Cơ hội & Báo giá.</p>`;
   const edit=n=>form(n?'Sửa ghi chú':'Thêm ghi chú',[['body','Nội dung *','textarea',null,n?.body||'']],async body=>{await api(n?'/notes/'+n.id:'/customers/'+id+'/notes',{method:n?'PUT':'POST',body});await refresh();});action(box,'[data-add-note]',()=>edit());action(box,'[data-edit-note]',b=>edit(data.notes.find(n=>String(n.id)===b.dataset.editNote)));
  }
  wireLinks(box);save();
 }
 async function selectTab(tab){state.tab=tab;save();await refresh();}
 data.users=await api('/users');
 // The API response intentionally omits unrelated user records; keep the permitted picker list locally.
 const users=data.users;refresh=async()=>{const y=window.scrollY;data=await api('/customers/'+id+'/360');data.users=users;await paint();window.scrollTo(0,y);};
 await paint();requestAnimationFrame(()=>window.scrollTo(0,state.scroll||0));return root;
};
// Specialist screens retain their established behavior and provide a contextual return path.
for(const name of ['conversation','opportunity','quote','tasks','progress','contact']){
 const previous=views[name];if(!previous)continue;
 views[name]=async(...args)=>{const el=await previous(...args);let r;try{r=JSON.parse(sessionStorage.getItem('customer360:return')||'null');}catch{}if(r&&r.key===profile360Key(r.id)&&location.hash.startsWith(r.destination))el.prepend($(`<a class="c360-back" href="#/customer/${r.id}">← Quay lại hồ sơ ${esc(r.name)}</a>`));return el;};
}

function readWorkState(id){try{return JSON.parse(sessionStorage.getItem(profile360Key(id))||'{}');}catch{return {};}}
function customerWorkHeader(c,tab){return $(`<section class="card work-customer-header"><div><h2>${esc(c.name)}</h2><p>${esc(c.kind==='org'?c.org_type||'Tổ chức':'Khách hàng cá nhân')} · Phụ trách: ${esc(c.owner_name||'Chưa phân công')}</p></div><a href="#/customer/${c.id}" data-profile>Hồ sơ đầy đủ →</a></section>`);}
function workScope(t,s){return (!s.opportunity||String(t.opp_id)===String(s.opportunity))&&(!s.person||String(t.contact_id)===String(s.person));}
function planStatus(s){return `<span class="tag ${workTone(s)}">${esc(workStateLabel(s))}</span>`;}
function nextPlan(tasks){return tasks.filter(t=>t.status!=='COMPLETED'&&!t.archived_at).sort((a,b)=>Number(late(b))-Number(late(a))||(Date.parse(a.due_at)||Infinity)-(Date.parse(b.due_at)||Infinity)||(b.priority==='Cao')-(a.priority==='Cao')||a.id-b.id)[0];}
function planGroup(t){return late(t)?'overdue':!t.due_at?'undated':vietnamDay(t.due_at)===vietnamDay(new Date())?'today':'upcoming';}

// One editor for entry points in the calendar, profile, journey and task details.
planTask=async function(customer=null,task=null,after=render,seed={}){
 if(!customer&&seed.customer_id)customer=(await api('/customers/'+seed.customer_id)).customer;
 if(!customer&&task?.customer_id)customer=(await api('/customers/'+task.customer_id)).customer;
 if(!customer&&!task&&!seed.internal){const cs=await api('/customers');form('Chọn khách hàng cho kế hoạch',[['customer_id','Khách hàng','select',[['','Việc nội bộ'],...cs.map(c=>[c.id,c.name])]]],async v=>{setTimeout(()=>planTask(cs.find(c=>String(c.id)===v.customer_id)||null,null,after,{...seed,internal:!v.customer_id}),0);});return;}
 const [users,d]=await Promise.all([api('/users'),customer?api('/customers/'+customer.id+'/360'):Promise.resolve(null)]),v=task||seed;
 const fields=[['title','Nội dung *','text',null,v.title||''],['kind','Loại tiếp xúc','select',['Công việc','Cuộc gọi','Cuộc họp','Demo'].map(x=>[x,x]),v.kind||'Công việc'],['due_at','Thời hạn (giờ Việt Nam)','datetime-local',null,workLocal(v.due_at)],['priority','Mức ưu tiên','select',[['Bình thường','Bình thường'],['Cao','Cao']],v.priority||'Bình thường'],['note','Nội dung chuẩn bị','textarea',null,v.note||'']];
 if(customer){fields.push(['contact_id','Người liên hệ','select',[['','Chưa chọn đầu mối'],...d.contacts.map(p=>[p.id,p.full_name])],v.contact_id||''],['opp_id','Cơ hội liên quan','select',[['','Chưa gắn cơ hội'],...d.opportunities.map(o=>[o.id,o.title])],v.opp_id||'']);}
 if(me.role==='leader'&&(!task||customer))fields.push(['assignee_id','Người thực hiện','select',users.filter(u=>u.active!==0&&['leader','sales'].includes(u.role)&&(!customer||u.role==='leader'||u.id===customer.owner_id)).map(u=>[u.id,u.name]),v.assignee_id||customer?.owner_id||me.id]);
 const key=crypto.randomUUID();form(task?'Sửa / đổi lịch kế hoạch':seed.parent_id?'Tạo công việc con':'Tạo kế hoạch tiếp xúc'+(customer?' · '+customer.name:''),fields,async body=>{
  body.due_at=workUTC(body.due_at);body.customer_id=customer?.id||null;body.request_key=key;
  if(seed.parent_id){body.parent_id=seed.parent_id;await api('/customers/'+customer.id+'/work-items',{body});}
  else await api('/tasks'+(task?'/'+task.id:''),{method:task?'PUT':'POST',body});
  await (after||render)();toast(task?'Đã cập nhật kế hoạch.':'Đã tạo một kế hoạch tiếp xúc.');
 });
};
async function completeContactPlan(t,after){const key=crypto.randomUUID();form('Hoàn thành · '+t.title,[['outcome','Kết quả chính *','textarea'],['feedback','Nhu cầu / phản hồi của khách hàng','textarea'],['next_step','Bước tiếp theo (nếu có)','textarea'],['prepare_next','Mở form bước tiếp theo sau khi lưu','check']],async body=>{await api('/tasks/'+t.id+'/complete-contact',{body:{...body,request_key:key}});await after();toast('Đã lưu kết quả và hoàn thành.');if(body.prepare_next)setTimeout(()=>planTask(null,null,after,{...t,id:undefined,title:body.next_step,customer_id:t.customer_id,internal:!t.customer_id,due_at:null,parent_id:null}),0);});}
openContactPlan=async function(task,after=render){
 const d=await api('/tasks/'+task.id+'/plan'),t=d.task;const dlg=$(`<dialog class="task-detail"><div class="section-heading"><h3>${esc(t.title)}</h3><button data-close aria-label="Đóng">×</button></div><p>${planStatus(t.status)} ${tag(t.kind)} ${late(t)?tag('Quá hạn'):''}</p><p>${esc(t.assignee_name||'Chưa phân công')} · ${esc(dueText(t.due_at))}</p><small>Ngày tạo: ${esc(taskCreatedText(t.created_at))}</small>${t.customer_id?`<p><a href="#/customer/${t.customer_id}">${esc(t.customer_name||'Hồ sơ khách hàng')} →</a></p>`:''}${t.opp_id?`<p><a href="#/opportunity/${t.opp_id}">Cơ hội liên quan →</a></p>`:''}<p class="preserve">${esc(t.note||'Chưa có ghi chú chuẩn bị.')}</p><div class="actions"><button data-edit>Sửa / đổi lịch</button>${!d.children.length?`<button class="major" data-complete>${t.status==='COMPLETED'?'Mở lại công việc':'Ghi kết quả & hoàn thành'}</button>`:'<small>Trạng thái được tính từ công việc con.</small>'}</div><details class="work-detail-extra"><summary>Tiến độ, công việc con và lịch sử</summary>${t.customer_id?`<div class="actions"><button data-child>Thêm công việc con</button><button data-update>Ghi nhận tiến độ</button>${!d.children.length&&t.status!=='COMPLETED'?'<button data-state>Đổi trạng thái xử lý</button>':''}</div>`:''}${d.children.map(c=>`<button class="activity-row" data-child-open="${c.id}">${esc(c.title)} ${planStatus(c.status)}</button>`).join('')}<div class="timeline">${d.updates.map(h=>`<article class="timeline-item"><strong>${esc(taskHistoryText(h.body))}</strong>${h.feedback?'<p>'+esc(h.feedback)+'</p>':''}${h.next_step?'<p>Bước tiếp theo: '+esc(h.next_step)+'</p>':''}<small>${dt(h.at)} · ${esc(h.actor||'Hệ thống')}</small></article>`).join('')||'<p>Chưa có cập nhật.</p>'}</div><button data-archive>Lưu trữ công việc</button></details></dialog>`);
 document.body.append(dlg);dlg.showModal();dlg.onclose=()=>dlg.remove();action(dlg,'[data-close]',()=>dlg.close());dlg.querySelectorAll('a').forEach(a=>a.onclick=()=>dlg.close());
 if(t.archived_at){dlg.insertAdjacentHTML('afterbegin','<p class="notice">Công việc đã lưu trữ. Lịch sử và kết quả vẫn được giữ nguyên.</p>');dlg.querySelectorAll('[data-edit],[data-complete],[data-child],[data-update],[data-state],[data-archive]').forEach(b=>b.remove());dlg.querySelector('details').open=true;}
 action(dlg,'[data-edit]',()=>{dlg.close();return planTask(null,t,after);});
 action(dlg,'[data-complete]',async()=>{if(t.status==='COMPLETED'){await api('/tasks/'+t.id+'/reopen',{body:{}});dlg.close();await after();}else{dlg.close();completeContactPlan(t,after);}});
 action(dlg,'[data-child-open]',b=>{dlg.close();return openContactPlan(d.children.find(c=>String(c.id)===b.dataset.childOpen),after);});
 action(dlg,'[data-child]',async()=>{dlg.close();const c=(await api('/customers/'+t.customer_id)).customer;return planTask(c,null,after,{parent_id:t.id,assignee_id:t.assignee_id,contact_id:t.contact_id,opp_id:t.opp_id});});
 action(dlg,'[data-update]',()=>{dlg.close();form('Ghi nhận tiến độ',[['body','Nội dung *','textarea']],async body=>{await api('/work-items/'+t.id+'/updates',{body});await after();});});
 action(dlg,'[data-state]',()=>{dlg.close();form('Trạng thái xử lý',[['status','Trạng thái','select',workStates.filter(([s])=>s!=='COMPLETED'),t.status]],async body=>{await api('/work-items/'+t.id+'/status',{body});await after();});});
 action(dlg,'[data-archive]',()=>{dlg.close();form('Lưu trữ công việc (có thể khôi phục)',[['reason','Lý do *','textarea']],async body=>{await api(t.customer_id?'/work-items/'+t.id+'/archive':'/lifecycle/tasks/'+t.id+'/archive',{body});await after();});});
};

async function renderPlanningPanel(box,tasks,customer,state,refresh){
 const key=profile360Key(customer?.id||'all')+':planning',saved=(()=>{try{return JSON.parse(sessionStorage.getItem(key)||'{}');}catch{return {};}})();
 const f={search:'',assignee:'',kind:'',time:'',status:'open',...saved};
 box.innerHTML=`<div class="section-heading"><div><h3>Kế hoạch tiếp xúc</h3><p class="small">Cần làm gì · Ai thực hiện · Khi nào</p></div>${!customer?.archived_at?'<button class="major" data-plan-new>Tạo kế hoạch tiếp xúc</button>':''}</div><div class="plan-filters"><label>Tìm kiếm<input type="search" data-filter="search" placeholder="Nội dung${customer?'':', khách hàng'}" value="${esc(f.search)}"></label><label>Người thực hiện<select data-filter="assignee">${options([['','Tất cả'],...new Map(tasks.map(t=>[t.assignee_id,[t.assignee_id||'unassigned',t.assignee_name||'Chưa phân công']])).values()],f.assignee)}</select></label><label>Loại tiếp xúc<select data-filter="kind">${options([['','Tất cả'],...['Công việc','Cuộc gọi','Cuộc họp','Demo'].map(s=>[s,s])],f.kind)}</select></label><label>Thời gian<select data-filter="time">${options([['','Tất cả'],['overdue','Quá hạn'],['today','Hôm nay'],['upcoming','Sắp tới'],['undated','Chưa có thời hạn']],f.time)}</select></label><label>Trạng thái<select data-filter="status">${options([['open','Đang mở'],...workStates,['all','Tất cả đang sử dụng']],f.status)}</select></label><button data-clear-plan>Xóa lọc</button></div><div data-plan-list></div><details class="work-detail-extra"><summary>Công cụ mở rộng</summary><div class="actions"><button data-plan-archive>Đã lưu trữ / Khôi phục</button>${customer?'<button data-plan-template>Áp dụng mẫu công việc</button><button data-delivery>Thông tin triển khai / dịch vụ đăng ký</button>':''}${me.role==='leader'?'<a href="#/work-templates">Quản lý mẫu công việc →</a>':''}</div><p class="small">Công việc con và lịch sử nằm trong chi tiết từng công việc. Việc đã lưu trữ có thể khôi phục; hệ thống chưa có trạng thái hủy riêng.</p></details>`;
 if(customer){const d=await api('/customers/'+customer.id+'/360'),scope=$(`<div class="plan-scope"><label>Cơ hội liên quan<select data-scope-opp>${options([['','Tất cả cơ hội'],...d.opportunities.map(o=>[o.id,o.title])],state.opportunity||'')}</select></label><label>Đầu mối<select data-scope-person>${options([['','Toàn đơn vị'],...d.contacts.map(p=>[p.id,p.full_name])],state.person||'')}</select></label></div>`);box.querySelector('.plan-filters').before(scope);for(const [attr,k] of [['opp','opportunity'],['person','person']])scope.querySelector('[data-scope-'+attr+']').onchange=e=>{state[k]=e.target.value;sessionStorage.setItem(profile360Key(customer.id),JSON.stringify({...readWorkState(customer.id),...state}));refresh();};}
 const filterWrap=$('<div class="plan-filter-body"></div>'),toggle=$('<button class="plan-filter-toggle" aria-expanded="false">Tìm kiếm & bộ lọc</button>');box.querySelector('.section-heading').after(toggle,filterWrap);const scopeEl=box.querySelector('.plan-scope');if(scopeEl)filterWrap.append(scopeEl);filterWrap.append(box.querySelector('.plan-filters'));toggle.onclick=()=>{const expanded=filterWrap.classList.toggle('expanded');toggle.setAttribute('aria-expanded',String(expanded));};
 const fill=()=>{sessionStorage.setItem(key,JSON.stringify(f));toggle.textContent='Tìm kiếm & bộ lọc · '+(f.status==='open'?'Đang mở':f.status==='all'?'Tất cả':workStateLabel(f.status))+(state.opportunity?' · Theo cơ hội':'');const rows=tasks.filter(t=>!t.archived_at&&workScope(t,state)&&(!f.search||[t.title,t.customer_name,t.assignee_name].join(' ').toLocaleLowerCase('vi').includes(f.search.toLocaleLowerCase('vi')))&&(!f.assignee||String(t.assignee_id||'unassigned')===f.assignee)&&(!f.kind||t.kind===f.kind)&&(!f.time||planGroup(t)===f.time)&&(f.status==='all'||f.status==='open'&&t.status!=='COMPLETED'||t.status===f.status));
  const groups=f.status==='open'?[['overdue','Quá hạn'],['today','Hôm nay'],['upcoming','Sắp tới'],['undated','Chưa có thời hạn']]:[['all',f.status==='COMPLETED'?'Đã hoàn thành':'Kết quả lọc']];
  box.querySelector('[data-plan-list]').innerHTML=groups.map(([k,label])=>{const list=rows.filter(t=>k==='all'||planGroup(t)===k).sort((a,b)=>(Date.parse(a.due_at)||Infinity)-(Date.parse(b.due_at)||Infinity)||a.id-b.id);return list.length?`<section class="plan-group"><h4>${label} <span>${list.length}</span></h4><div class="plan-table"><table><thead><tr><th>Nội dung</th>${customer?'':'<th>Khách hàng</th>'}<th>Loại tiếp xúc</th><th>Người thực hiện</th><th>Thời gian</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>${list.map(t=>`<tr><td data-label="Nội dung"><strong>${esc(t.title)}</strong>${t.parent_id?'<small>Công việc con</small>':''}${t.priority==='Cao'?'<small>↑ Ưu tiên cao</small>':''}</td>${customer?'':`<td data-label="Khách hàng">${t.customer_id?`<a href="#/customer/${t.customer_id}">${esc(t.customer_name)}</a>`:'Việc nội bộ'}</td>`}<td data-label="Loại">${esc(t.kind)}</td><td data-label="Người thực hiện">${esc(t.assignee_name||'Chưa phân công')}</td><td data-label="Thời gian">${esc(dueText(t.due_at))}</td><td data-label="Trạng thái">${planStatus(t.status)}</td><td><button data-plan-open="${t.id}">Mở công việc</button></td></tr>`).join('')}</tbody></table></div></section>`:'';}).join('')||empty('Không có kế hoạch phù hợp','Đổi bộ lọc hoặc tạo kế hoạch tiếp xúc.');
  action(box,'[data-plan-open]',b=>openContactPlan(tasks.find(t=>String(t.id)===b.dataset.planOpen),refresh));
 };
 fill();box.querySelectorAll('[data-filter]').forEach(el=>el[el.type==='search'?'oninput':'onchange']=()=>{f[el.dataset.filter]=el.value;fill();});action(box,'[data-clear-plan]',()=>{sessionStorage.removeItem(key);return renderPlanningPanel(box,tasks,customer,state,refresh);});
 action(box,'[data-plan-new]',()=>planTask(customer,null,refresh,{contact_id:state.person,opp_id:state.opportunity}));action(box,'[data-plan-archive]',async()=>{if(!customer)return archivedRecords('tasks');const p=(await api('/customer-progress')).find(p=>p.customer.id===customer.id),rows=p.tasks.filter(t=>t.archived_at&&workScope(t,state));const d=$(`<dialog class="task-detail"><h3>Công việc đã lưu trữ · ${esc(customer.name)}</h3>${rows.map(t=>`<div class="balance"><strong>${esc(t.title)}</strong><button data-restore="${t.id}">Khôi phục</button></div>`).join('')||'<p>Chưa có việc đã lưu trữ trong phạm vi chọn.</p>'}<button data-close>Đóng</button></dialog>`);document.body.append(d);d.showModal();d.onclose=()=>d.remove();action(d,'[data-close]',()=>d.close());action(d,'[data-restore]',async b=>{await api('/work-items/'+b.dataset.restore+'/restore',{body:{}});d.close();await refresh();});});
 action(box,'[data-plan-template]',async()=>{const ts=await api('/work-templates');if(!ts.length)return toast('Trưởng nhóm cần tạo mẫu trước.');const request_key=crypto.randomUUID();form('Áp dụng mẫu · '+customer.name,[['template_id','Mẫu','select',ts.map(t=>[t.id,t.name])]],async body=>{await api('/customers/'+customer.id+'/apply-work-template',{body:{...body,request_key,contact_id:state.person,opp_id:state.opportunity}});await refresh();});});
 action(box,'[data-delivery]',async()=>{const p=(await api('/customer-progress')).find(p=>p.customer.id===customer.id);form('Thông tin triển khai',[['platform','Nền tảng','text',null,p.platform],['address','Địa chỉ triển khai','text',null,p.address],['services','Dịch vụ đăng ký (mỗi dòng một dịch vụ)','textarea',null,p.services.join('\n')]],async body=>{body.services=body.services.split('\n').map(s=>s.trim()).filter(Boolean);await api('/customers/'+customer.id+'/delivery',{method:'PUT',body});await refresh();});});
}

async function renderJourneyPanel(box,data,state,refresh,change){
 const c=data.customer,os=data.opportunities,selected=os.find(o=>String(o.id)===String(state.opportunity)),tasks=data.tasks.filter(t=>workScope(t,state)),open=tasks.filter(t=>t.status!=='COMPLETED'),next=nextPlan(tasks),events=data.milestones.filter(e=>workScope(e,state));
 box.innerHTML=`<section class="journey-section"><div class="section-heading"><h3>1. Trạng thái hiện tại</h3><button data-journey-refresh>Làm mới</button></div><div class="journey-status"><div><small>QUAN HỆ KHÁCH HÀNG</small><p><strong>${c.do_not_contact?'Không liên hệ':c.needs_followup?'Cần tiếp tục chăm sóc':'Đã xử lý nhu cầu hiện tại'}</strong></p><small>NHU CẦU / SẢN PHẨM</small><p>${esc(c.interest||'Chưa ghi nhận')}</p></div><div><label>Cơ hội đang theo dõi<select data-journey-opp>${options([['','Toàn khách hàng · tất cả cơ hội'],...os.map(o=>[o.id,o.title])],state.opportunity||'')}</select></label><p>${selected?tag(selected.stage)+' <a href="#/opportunity/'+selected.id+'">Mở cơ hội →</a>':os.length+' cơ hội riêng biệt · Chọn một cơ hội để xem giai đoạn.'}</p>${selected&&!c.archived_at?'<button data-journey-stage>Đổi giai đoạn cơ hội</button>':''}</div></div>${data.contacts.length?`<label class="journey-person">Đầu mối<select data-journey-person>${options([['','Toàn đơn vị'],...data.contacts.map(p=>[p.id,p.full_name])],state.person||'')}</select></label>`:''}</section><section class="journey-section"><div class="section-heading"><h3>2. Bước tiếp theo</h3><span class="small">${open.length} việc còn mở</span></div>${next?`<div class="journey-next"><div><h4>${esc(next.title)}</h4><p>${esc(next.assignee_name||'Chưa phân công')} · ${esc(dueText(next.due_at))}</p>${late(next)?tag('Quá hạn'):planStatus(next.status)}</div><button class="major" data-journey-open>Mở công việc</button></div>`:`<p>Chưa có kế hoạch tiếp theo</p>${!c.archived_at?'<button class="major" data-journey-create>Tạo kế hoạch tiếp xúc</button>':''}`}<p class="small">Ưu tiên việc quá hạn, rồi hạn gần nhất; cùng hạn ưu tiên việc mức Cao.</p><a href="#/tasks/customer-${c.id}" data-view-plans>Xem kế hoạch →</a></section><section class="journey-section"><h3>3. Các mốc đã thực hiện</h3><div class="timeline">${events.map(e=>`<article class="timeline-item"><strong>${esc(e.title)}</strong><small>${dt(e.at)} · ${esc(e.actor||'Chưa ghi nhận người thực hiện')}</small>${e.detail?'<p class="preserve">'+esc(e.detail)+'</p>':''}${e.href.startsWith('#/customer/')?`<button data-milestone="${esc(e.id)}">Xem bản ghi</button>`:`<a href="${e.href}">Mở bản ghi gốc →</a>`}</article>`).join('')||empty('Chưa có mốc nghiệp vụ trong phạm vi chọn')}<p class="small">Chưa triển khai ghi nhận thanh toán và hồ sơ hợp đồng. Xác nhận ký hợp đồng được theo dõi trong giai đoạn cơ hội. Các chỉnh sửa nhỏ vẫn nằm trong lịch sử chi tiết.</p></div></section>`;
 action(box,'[data-journey-refresh]',refresh);action(box,'[data-journey-open]',()=>openContactPlan(next,refresh));action(box,'[data-journey-create]',()=>planTask(c,null,refresh,{contact_id:state.person,opp_id:state.opportunity}));
 box.querySelectorAll('.timeline a[href^="#/tasks/"]').forEach(a=>a.onclick=e=>{e.preventDefault();openContactPlan({id:Number(a.getAttribute('href').split('/').at(-1))},refresh).catch(e=>toast(e.message));});
 if(!c.archived_at){const edit=$('<button>Cập nhật quan hệ / nhu cầu</button>');box.querySelector('.journey-status>div').append(edit);edit.onclick=()=>editDirectoryCustomer(c.id,refresh);}
 box.querySelector('[data-journey-opp]').onchange=e=>{state.opportunity=e.target.value;change();};const person=box.querySelector('[data-journey-person]');if(person)person.onchange=e=>{state.person=e.target.value;change();};
 action(box,'[data-journey-stage]',()=>form('Đổi giai đoạn · '+selected.title,[['stage','Giai đoạn','select',STAGES.map(s=>[s,s]),selected.stage]],async b=>{setTimeout(()=>changeOpportunityStage(selected,b.stage,refresh),0);}));
 action(box,'[data-milestone]',b=>{const e=events.find(e=>e.id===b.dataset.milestone);const d=$(`<dialog class="task-detail"><h3>${esc(e.type)}</h3><p class="preserve">${esc(e.title)}</p><p class="preserve">${esc(e.detail||'')}</p><small>${dt(e.at)} · ${esc(e.actor||'')}</small><button data-close>Đóng</button></dialog>`);document.body.append(d);d.showModal();d.onclose=()=>d.remove();action(d,'[data-close]',()=>d.close());});
}

views.tasks=async focus=>{
 const customerId=focus?.startsWith('customer-')?Number(focus.slice(9)):null,customer=customerId?(await api('/customers/'+customerId)).customer:null,state=customer?readWorkState(customerId):{};
 const el=$(`<div>${pageHeading('Kế hoạch tiếp xúc','Theo dõi việc cần làm và ghi nhận kết quả.')}<section class="card" data-planning></section></div>`);
 if(customer){sessionStorage.setItem(profile360Key('journey-selection'),String(customerId));el.querySelector('.page-heading').replaceWith(customerWorkHeader(customer,'tasks'));el.querySelector('[data-planning]').before($(`<div class="actions"><a href="#/progress/${customerId}">Tiến trình khách hàng →</a><a href="#/tasks">Tất cả kế hoạch →</a></div>`));}
 const refresh=async()=>{const tasks=await api('/tasks');await renderPlanningPanel(el.querySelector('[data-planning]'),customer?tasks.filter(t=>t.customer_id===customerId):tasks,customer,state,refresh);};await refresh();
 if(focus&&!customerId){const d=await api('/tasks/'+Number(focus)+'/plan');setTimeout(()=>openContactPlan(d.task,refresh),0);}
 return el;
};
views.progress=async focus=>{
 await loadPipelineStages();const cs=await api('/customers'),key=profile360Key('journey-selection');let selected=focus||sessionStorage.getItem(key)||'';if(!cs.some(c=>String(c.id)===String(selected)))selected='';
 const el=$(`<div>${pageHeading('Tiến trình khách hàng','Trạng thái hiện tại · Bước tiếp theo · Các mốc đã thực hiện')}<div class="card journey-picker"><label>Tìm khách hàng<input type="search" data-search-customer placeholder="Tên khách hàng hoặc người phụ trách"></label><label>Khách hàng<select data-pick-customer>${options([['','Chọn khách hàng'],...cs.map(c=>[c.id,c.name])],selected)}</select></label></div><div data-journey></div></div>`);
 const load=async()=>{const target=el.querySelector('[data-journey]');if(!selected){target.innerHTML=empty('Chọn một khách hàng để xem tiến trình');return;}const data=await api('/customers/'+selected+'/360'),state=readWorkState(selected);target.replaceChildren(customerWorkHeader(data.customer,'overview'));const pane=$('<section class="card"></section>');target.append(pane);const change=()=>{sessionStorage.setItem(profile360Key(selected),JSON.stringify(state));return load();};await renderJourneyPanel(pane,data,state,load,change);};
 el.querySelector('[data-pick-customer]').onchange=e=>{selected=e.target.value;sessionStorage.setItem(key,selected);load().catch(e=>toast(e.message));};el.querySelector('[data-search-customer]').oninput=e=>{const term=e.target.value.toLocaleLowerCase('vi');el.querySelector('[data-pick-customer]').innerHTML=options([['','Chọn khách hàng'],...cs.filter(c=>String(c.id)===String(selected)||[c.name,c.owner_name].join(' ').toLocaleLowerCase('vi').includes(term)).map(c=>[c.id,c.name])],selected);};await load();return el;
};




