// Directory presentation shares the organization/contact APIs with the 360° view.
const directoryPreferenceKey=()=>`directory:${me.company?.code||'ivitech'}:${me.id}`;
function directoryRead(){try{return JSON.parse(sessionStorage.getItem(directoryPreferenceKey()))||{};}catch{return {};}}
function directoryRemember(patch){sessionStorage.setItem(directoryPreferenceKey(),JSON.stringify({...directoryRead(),...patch}));}
function editDirectoryContact(c,orgId,after){form(c?'Sửa người liên hệ':'Tạo người liên hệ mới',orgContactFields(c).filter(f=>!c?.detached_at||f[0]!=='is_primary'),async body=>{await api(c?'/contacts/'+c.id:'/organizations/'+orgId+'/contacts',{method:c?'PUT':'POST',body:{...body,...(c?{version:c.version}:{})}});toast('Đã lưu người liên hệ. Nếu đang lọc, liên hệ có thể không khớp bộ lọc.');after();});}
function unlinkDirectoryContact(c,after){form('Gỡ liên hệ khỏi đơn vị — '+c.full_name,[['reason','Lý do * — Hồ sơ cá nhân và lịch sử vẫn được giữ trong CRM','textarea']],async body=>{await api('/contacts/'+c.id+'/unlink',{body:{...body,version:c.version}});toast('Đã gỡ liên kết. Hồ sơ còn trong mục Liên hệ chưa gắn đơn vị.');after();});}
function addDirectoryContact(org,after){
 const d=$(`<dialog class="directory-picker"><h2>Thêm liên hệ</h2><p>Đơn vị: <strong>${esc(org.name)}</strong></p><div class="actions"><button data-existing>Chọn liên hệ có sẵn</button><button class="major" data-create>Tạo liên hệ mới</button></div><div data-lookup></div><div class="actions"><button data-close>Đóng</button></div></dialog>`);document.body.append(d);d.showModal();d.onclose=()=>d.remove();action(d,'[data-close]',()=>d.close());action(d,'[data-create]',()=>{d.close();editDirectoryContact(null,org.id,after);});
 action(d,'[data-existing]',()=>{
  const box=d.querySelector('[data-lookup]');box.innerHTML='<p class="small">Chọn liên hệ chưa gắn đơn vị. Liên hệ đang thuộc đơn vị khác sẽ không bị tự chuyển.</p><input type="search" aria-label="Tìm liên hệ có sẵn" placeholder="Tên, điện thoại hoặc email…"><div data-results></div>';let pg=1,seq=0;
  async function load(){const n=++seq;const b=box.querySelector('[data-results]');b.innerHTML='<p role="status">Đang tìm liên hệ…</p>';try{const r=await api('/directory/contacts?organization_id='+org.id+'&search='+encodeURIComponent(box.querySelector('input').value)+'&page='+pg);if(n!==seq||!d.isConnected)return;b.innerHTML=r.items.map(p=>`<div class="directory-lookup-row"><div><strong>${esc(p.full_name)}</strong><small>${esc([p.phone,p.email].filter(Boolean).join(' · '))}</small><small>${p.link_status==='available'?'Chưa gắn đơn vị':p.link_status==='linked'?'Đã thuộc đơn vị này':'Đang thuộc '+esc(p.organization_name)}</small></div><button data-link="${p.id}" ${p.link_status==='available'?'':'disabled'}>Chọn</button></div>`).join('')||empty('Không có liên hệ phù hợp');b.insertAdjacentHTML('beforeend',`<div class="actions"><button data-prev ${r.page<=1?'disabled':''}>Trước</button><span>Trang ${r.page}/${r.pages}</span><button data-next ${r.page>=r.pages?'disabled':''}>Sau</button></div>`);action(b,'[data-prev]',()=>{pg--;return load();});action(b,'[data-next]',()=>{pg++;return load();});action(b,'[data-link]',btn=>{const c=r.items.find(c=>String(c.id)===btn.dataset.link);d.close();form('Liên kết '+c.full_name+' vào '+org.name,[['job_title','Chức danh tại đơn vị','text',null,''],['department','Phòng / ban','text',null,''],['contact_role','Vai trò','select',orgContactRoles.map(x=>[x,x])],['is_primary','Đầu mối chính','check']],async body=>{await api('/organizations/'+org.id+'/link-contact',{body:{...body,contact_id:c.id,version:c.version}});toast('Đã liên kết hồ sơ có sẵn, không tạo bản sao.');after();});});}catch(e){b.innerHTML=`<p class="err">${esc(e.message)}</p><button data-retry>Thử lại</button>`;action(b,'[data-retry]',load);}}
  let timer;box.querySelector('input').oninput=()=>{pg=1;clearTimeout(timer);timer=setTimeout(load,200);};load();
 });
}
function directoryContactsTable(rows,matched=false){return `<div class="directory-contact-scroll"><table class="directory-contact-table"><thead><tr><th>Họ tên / vai trò</th><th>Chức danh · Phòng/Ban</th><th>Điện thoại / Email</th><th>Ghi chú</th><th>Thao tác</th></tr></thead><tbody>${rows.map(p=>`<tr><td><a href="#/contact/${p.id}"><strong>${esc(p.full_name)}</strong></a><small>${esc(p.contact_role)}</small>${p.is_primary?tag('Đầu mối chính'):''}${matched?'<span class="tag status-info">Khớp tìm kiếm</span>':''}</td><td>${esc(p.job_title||'Chưa bổ sung')}<small>${esc(p.department||'Chưa bổ sung phòng/ban')}</small></td><td>${esc(p.phone||'Chưa bổ sung')}<small>${esc(p.email||'Chưa bổ sung email')}</small></td><td><details><summary>Xem ghi chú</summary><p class="preserve">${esc(p.note||'Chưa có ghi chú')}</p></details></td><td><div class="actions"><button data-contact-edit="${p.id}" aria-label="Sửa liên hệ ${esc(p.full_name)}">Sửa</button><button data-contact-unlink="${p.id}" title="Gỡ liên hệ khỏi đơn vị" aria-label="Gỡ ${esc(p.full_name)} khỏi đơn vị">Gỡ liên kết</button></div></td></tr>`).join('')}</tbody></table></div>`;}
function customerRowActions(c){return ['sales','leader'].includes(me.role)?`<div class="actions customer-row-actions"><button data-customer-edit="${c.id}" aria-label="Sửa khách hàng ${esc(c.name)}">Sửa</button><button class="customer-delete" data-customer-delete="${c.id}" aria-label="Xóa khách hàng ${esc(c.name)}">Xóa</button></div>`:'';}
async function editDirectoryCustomer(id,after=render){const d=await api('/customers/'+id),c=d.customer;if(c.archived_at)throw Error('Khôi phục khách hàng trước khi sửa.');form('Sửa khách hàng — '+c.name,customerFields(c),async body=>{await api('/customers/'+id,{method:'PUT',body});toast('Đã cập nhật khách hàng.');after();});}
function deleteDirectoryCustomer(c,after=render){form('Xóa khách hàng — '+c.name,[['reason','Lý do xóa * — Khách được đưa vào Đã xóa / Khôi phục; lịch sử, báo giá và công việc vẫn được giữ.','textarea']],async body=>{await api('/lifecycle/customers/'+c.id+'/archive',{body});toast('Đã xóa khỏi danh sách đang hoạt động. Có thể khôi phục trong Đã xóa / Khôi phục.');after();});const submit=[...document.querySelectorAll('dialog')].at(-1)?.querySelector('[type=submit]');if(submit)submit.textContent='Xác nhận xóa';}
views.customers=async routeId=>{
 const preferenceKey=directoryPreferenceKey(),pref=directoryRead(),s={mode:'group',kind:'all',search:'',owner:'all',care:'all',services:[],page:1,expanded:[],...pref};let sequence=0,detachedSequence=0;const paneState=new Map(Object.entries(s.contactPages||{}).map(([id,p])=>[Number(id),p]));
 const el=$(`<div data-server-directory="true">${pageHeading('Danh bạ khách hàng','Xem đơn vị và đầu mối liên hệ trong cùng một nơi.',`<button id="new" class="major">+ Thêm khách hàng</button>${me.role==='leader'?'<button id="import">Nhập CSV</button>':''}`)}<section class="list-tools"><label>Tìm đơn vị hoặc người liên hệ<input type="search" id="directory-search" placeholder="Tên, điện thoại, email…" value="${esc(s.search)}"></label><label>Người phụ trách<select id="directory-owner"></select></label><label>Chăm sóc<select id="directory-care">${options([['all','Tất cả'],['followup','Cần tiếp tục xử lý'],['no-contact','Không liên hệ']],s.care)}</select></label><details><summary>Dịch vụ quan tâm (chọn nhiều)</summary><div class="list-filter-options" data-services></div></details><button data-clear>Xóa bộ lọc</button></section><div class="compact-counts" data-counts></div><div class="directory-switch"><div class="segments" role="tablist" aria-label="Loại khách hàng">${[['all','Tất cả'],['org','Tổ chức'],['person','Cá nhân']].map(([k,n])=>`<button data-kind="${k}" role="tab" aria-selected="${s.kind===k}">${n}</button>`).join('')}</div><div class="segments" role="group" aria-label="Dạng xem danh bạ">${[['list','Danh sách'],['group','Theo doanh nghiệp/đơn vị']].map(([k,n])=>`<button data-mode="${k}" aria-pressed="${s.mode===k}" class="${s.mode===k?'selected':''}">${n}</button>`).join('')}</div></div><div data-directory-results></div><section class="card" data-detached></section></div>`);
 const save=()=>sessionStorage.setItem(preferenceKey,JSON.stringify(s));const rememberScroll=()=>sessionStorage.setItem(preferenceKey,JSON.stringify({...s,scroll:window.scrollY}));el.addEventListener('click',e=>{if(e.target.closest('a[href^="#/"]'))rememberScroll();});
 async function renderPane(card,c){const box=card.querySelector('[data-pane]');const wasSearching=box.querySelector('[data-contact-search]')===document.activeElement;const p=paneState.get(c.id)||{page:1,search:c.matched_contacts?s.search:''};paneState.set(c.id,p);s.contactPages=Object.fromEntries([...paneState].map(([id,v])=>[id,{page:v.page,search:v.search}]));save();const n=(p.seq||0)+1;p.seq=n;box.innerHTML='<p role="status">Đang tải thông tin và liên hệ…</p>';
  try{const r=await api('/organizations/'+c.id+'/contact-page?page='+p.page+'&search='+encodeURIComponent(p.search));if(p.seq!==n||!el.contains(card))return;
   box.innerHTML=`<section><div class="section-heading"><h3>Thông tin đơn vị</h3><button data-org-edit>Sửa thông tin đơn vị</button></div><dl class="org-detail-list">${[['Tên đơn vị',c.name],['Địa chỉ',r.details.address],['Điện thoại chung',c.phone],['Email chung',c.email],['Người phụ trách',c.owner_name]].map(([k,v])=>`<div><dt>${k}</dt><dd>${esc(v||'Chưa bổ sung')}</dd></div>`).join('')}</dl></section><section class="directory-contacts"><div class="section-heading"><h3>Đầu mối liên hệ (${r.contact_count})</h3><button data-add-contact>+ Thêm liên hệ</button></div><label>Tìm trong liên hệ của đơn vị<input data-contact-search type="search" value="${esc(p.search)}" placeholder="Tên, chức danh, điện thoại…"></label>${p.search?`<p class="hint">Đang hiển thị ${r.items.length}/${r.total} liên hệ phù hợp. Tổng ${r.contact_count} liên hệ được phép xem. <button data-all-contacts>Xem tất cả liên hệ được phép</button></p>`:''}${r.items.length?directoryContactsTable(r.items,!!p.search):empty(p.search?'Không có liên hệ phù hợp với bộ lọc':'Chưa có liên hệ trong đơn vị này')}<div class="actions"><button data-contact-prev ${r.page<=1?'disabled':''}>Trước</button><span>Trang ${r.page}/${r.pages}</span><button data-contact-next ${r.page>=r.pages?'disabled':''}>Sau</button></div></section>`;
   const refresh=()=>load();action(box,'[data-add-contact]',()=>addDirectoryContact(c,refresh));action(box,'[data-contact-edit]',b=>editDirectoryContact(r.items.find(p=>String(p.id)===b.dataset.contactEdit),c.id,refresh));action(box,'[data-contact-unlink]',b=>unlinkDirectoryContact(r.items.find(p=>String(p.id)===b.dataset.contactUnlink),refresh));
   action(box,'[data-org-edit]',()=>form('Sửa thông tin đơn vị', [['name','Tên đơn vị *','text',null,c.name],['phone','Điện thoại chung','text',null,c.phone],['email','Email chung','email',null,c.email],['address','Địa chỉ','textarea',null,r.details.address]],async body=>{await api('/organizations/'+c.id+'/directory-details',{method:'PUT',body:{...body,expected_name:c.name,expected_phone:c.phone||'',expected_email:c.email||'',expected_address:r.details.address||''}});toast('Đã cập nhật thông tin đơn vị.');load();}));
   action(box,'[data-contact-prev]',()=>{p.page--;return renderPane(card,c);});action(box,'[data-contact-next]',()=>{p.page++;return renderPane(card,c);});action(box,'[data-all-contacts]',()=>{p.search='';p.page=1;return renderPane(card,c);});let timer;box.querySelector('[data-contact-search]').oninput=e=>{p.search=e.target.value;p.page=1;clearTimeout(timer);timer=setTimeout(()=>renderPane(card,c),450);};if(wasSearching){const input=box.querySelector('[data-contact-search]');input.focus();input.setSelectionRange(input.value.length,input.value.length);}
  }catch(e){box.innerHTML=`<p class="err">${esc(e.message)}</p><button data-retry>Thử lại</button>`;action(box,'[data-retry]',()=>renderPane(card,c));}}
 async function detached(page=1){const request=++detachedSequence;const box=el.querySelector('[data-detached]');try{const r=await api('/directory/contacts?detached=1&page='+page+'&search='+encodeURIComponent(s.search)+'&owner='+encodeURIComponent(s.owner)+'&care='+s.care+s.services.map(v=>'&service='+encodeURIComponent(v)).join(''));if(request!==detachedSequence)return;box.hidden=s.kind==='org';box.innerHTML=`<h3>Liên hệ chưa gắn đơn vị (${r.total})</h3><p class="small">Các hồ sơ đã gỡ liên kết vẫn được giữ trong phạm vi phụ trách hiện có.</p>${r.items.map(c=>`<div class="directory-lookup-row"><a href="#/contact/${c.id}"><strong>${esc(c.full_name)}</strong></a><span>${esc(c.phone||c.email||'Chưa bổ sung liên hệ')}</span></div>`).join('')||empty('Chưa có liên hệ chưa gắn đơn vị phù hợp')}<div class="actions"><button data-detached-prev ${r.page<=1?'disabled':''}>Trước</button><span>Trang ${r.page}/${r.pages}</span><button data-detached-next ${r.page>=r.pages?'disabled':''}>Sau</button></div>`;action(box,'[data-detached-prev]',()=>detached(r.page-1));action(box,'[data-detached-next]',()=>detached(r.page+1));}catch(e){box.innerHTML=`<p class="err">${esc(e.message)}</p>`;}}
 async function load(){const n=++sequence;save();const box=el.querySelector('[data-directory-results]');box.setAttribute('aria-busy','true');try{const params=new URLSearchParams({search:s.search,kind:s.kind,owner:s.owner,care:s.care,page:s.page});s.services.forEach(x=>params.append('service',x));const r=await api('/directory?'+params);if(n!==sequence)return;s.page=r.page;save();el.querySelector('[data-counts]').innerHTML=[[r.summary.total,'khách trong phạm vi'],[r.summary.orgs,'tổ chức'],[r.summary.people,'cá nhân'],[r.summary.unassigned,'chờ phân công']].map(([v,l])=>`<div><strong>${v}</strong>${l}</div>`).join('');el.querySelector('#directory-owner').innerHTML=options([['all','Tất cả người phụ trách'],['none','Chưa phân công'],...r.owners],s.owner);el.querySelector('[data-services]').innerHTML=r.services.map((v,i)=>`<label><input type="checkbox" data-service="${i}" ${s.services.includes(v)?'checked':''}>${esc(v)}</label>`).join('');el.querySelectorAll('[data-service]').forEach(b=>b.onchange=()=>{const v=r.services[+b.dataset.service];s.services=b.checked?[...s.services,v]:s.services.filter(x=>x!==v);s.page=1;load();});
  box.innerHTML=s.mode==='list'?`<section class="card table-card"><table><thead><tr><th>Khách hàng</th><th>Liên hệ</th><th>Dịch vụ quan tâm</th><th>Chăm sóc</th><th>Phụ trách</th><th>Thao tác</th></tr></thead><tbody>${r.items.map(c=>`<tr><td><div class="identity">${avatar(c.name)}<div><a href="#/customer/${c.id}"><strong>${esc(c.name)}</strong></a><small>${c.kind==='person'?'Cá nhân':esc(c.org_type||'Tổ chức')}</small>${c.matched_contacts?`<small>${c.matched_contacts} liên hệ khớp tìm kiếm</small>`:''}</div></div></td><td>${esc(c.phone||'Chưa bổ sung')}<small>${esc(c.email||'')}</small></td><td>${esc(c.interest||'Chưa ghi nhận')}</td><td>${tag(c.do_not_contact?'Không liên hệ':c.needs_followup?'Cần xử lý':'Đã xử lý')}</td><td>${esc(c.owner_name||'Chưa phân công')}</td><td>${customerRowActions(c)}</td></tr>`).join('')||'<tr><td colspan="6">Không có khách hàng phù hợp</td></tr>'}</tbody></table></section>`:r.items.map(c=>c.kind==='person'?`<section class="card directory-person"><div class="identity">${avatar(c.name)}<div><a href="#/customer/${c.id}"><strong>${esc(c.name)}</strong></a><small>Khách hàng cá nhân độc lập · ${esc(c.owner_name||'Chưa phân công')}</small></div></div>${customerRowActions(c)}</section>`:`<article class="directory-unit" data-org="${c.id}"><div class="directory-unit-head"><button class="directory-expand" aria-expanded="${s.expanded.includes(c.id)}" aria-controls="org-pane-${c.id}" aria-label="Mở/thu gọn ${esc(c.name)}"><span aria-hidden="true">${s.expanded.includes(c.id)?'▾':'▸'}</span>${avatar(c.name)}<span class="directory-unit-name"><strong>${esc(c.name)}</strong><small>${esc(c.org_type||'Tổ chức')}${c.address?' · '+esc(c.address):''}</small></span>${tag(c.contact_count+' liên hệ')}</button><div class="directory-customer-tools"><a href="#/customer/${c.id}">Mở hồ sơ 360° →</a>${customerRowActions(c)}</div></div><div id="org-pane-${c.id}" data-pane ${s.expanded.includes(c.id)?'':'hidden'}></div></article>`).join('')||empty('Không có khách hàng phù hợp','Thử xóa bộ lọc.');
  box.insertAdjacentHTML('beforeend',`<div class="actions directory-pagination"><button data-prev ${r.page<=1?'disabled':''}>Trang trước</button><span>Trang ${r.page}/${r.pages} · ${r.total} hồ sơ phù hợp (không tính số liên hệ)</span><button data-next ${r.page>=r.pages?'disabled':''}>Trang sau</button></div>`);
  action(box,'[data-customer-edit]',b=>editDirectoryCustomer(b.dataset.customerEdit,load));action(box,'[data-customer-delete]',b=>deleteDirectoryCustomer(r.items.find(c=>String(c.id)===b.dataset.customerDelete),load));
  action(box,'[data-prev]',()=>{s.page--;return load();});action(box,'[data-next]',()=>{s.page++;return load();});box.querySelectorAll('[data-org]').forEach(card=>{const c=r.items.find(c=>String(c.id)===card.dataset.org),btn=card.querySelector('.directory-expand'),pane=card.querySelector('[data-pane]');btn.onclick=()=>{const open=btn.getAttribute('aria-expanded')!=='true';btn.setAttribute('aria-expanded',String(open));btn.querySelector('span').textContent=open?'▾':'▸';pane.hidden=!open;s.expanded=open?[...new Set([...s.expanded,c.id])]:s.expanded.filter(id=>id!==c.id);save();if(open)renderPane(card,c);};if(s.expanded.includes(c.id))renderPane(card,c);});detached();
 }catch(e){box.innerHTML=`<p class="err">${esc(e.message)}</p><button data-retry>Thử lại</button>`;action(box,'[data-retry]',load);}finally{box.removeAttribute('aria-busy');}}
 let timer;el.querySelector('#directory-search').oninput=e=>{s.search=e.target.value;s.page=1;paneState.clear();clearTimeout(timer);timer=setTimeout(load,250);};el.querySelector('#directory-owner').onchange=e=>{s.owner=e.target.value;s.page=1;load();};el.querySelector('#directory-care').onchange=e=>{s.care=e.target.value;s.page=1;load();};action(el,'[data-clear]',()=>{s.search='';s.owner='all';s.care='all';s.services=[];s.page=1;el.querySelector('#directory-search').value='';el.querySelector('#directory-care').value='all';paneState.clear();return load();});
 action(el,'[data-kind]',b=>{s.kind=b.dataset.kind;s.page=1;el.querySelectorAll('[data-kind]').forEach(x=>x.setAttribute('aria-selected',String(x===b)));return load();});action(el,'[data-mode]',b=>{s.mode=b.dataset.mode;el.querySelectorAll('[data-mode]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});return load();});
 const create=()=>form('Thêm khách hàng',[['kind','Loại khách','select',[['org','Tổ chức / cơ quan'],['person','Cá nhân']]],...customerFields(),['is_sample','Đây là dữ liệu mẫu','check',null,true]],async body=>{const r=await api('/customers',{body});go('#/customer/'+r.id);});action(el,'#new',create);action(el,'#import',()=>go('#/import'));await load();if(routeId==='new')setTimeout(create,0);else if(s.scroll)setTimeout(()=>window.scrollTo(0,s.scroll),0);return el;
};
views.contact=async id=>{
 const d=await api('/contacts/'+id),c=d.contact;const el=$(`<div>${pageHeading(c.full_name,'Hồ sơ người liên hệ',`<a href="#/customers">← Về Danh bạ</a>${d.can_edit?'<button data-edit>Chỉnh sửa</button>':''}`)}<div class="profile-grid"><section class="card"><h3>Thông tin cá nhân</h3><dl class="org-detail-list">${[['Họ tên',c.full_name],['Điện thoại',c.phone],['Email',c.email],['Trạng thái',c.archived_at?'Đã ngừng liên hệ':c.detached_at?'Chưa gắn đơn vị':'Đang liên kết']].map(([k,v])=>`<div><dt>${k}</dt><dd>${esc(v||'Chưa bổ sung')}</dd></div>`).join('')}</dl></section><section class="card"><h3>Đơn vị & vai trò</h3>${d.organization?`<a href="#/customer/${d.organization.id}">${esc(d.organization.name)}</a><dl class="org-detail-list">${[['Chức danh',c.job_title],['Phòng/Ban',c.department],['Vai trò',c.contact_role]].map(([k,v])=>`<div><dt>${k}</dt><dd>${esc(v||'Chưa bổ sung')}</dd></div>`).join('')}</dl>${d.can_edit?'<button data-unlink>Gỡ liên hệ khỏi đơn vị</button>':''}`:`<p>Chưa gắn với đơn vị. Có thể chọn hồ sơ này từ nút “Thêm liên hệ” trong Danh bạ.</p><p class="small">Phạm vi quản lý hiện tại: ${esc(d.scope_organization.name)}.</p>`}<h3>Ghi chú</h3><p class="preserve">${esc(c.note||'Chưa có ghi chú')}</p></section></div><section class="card"><h3>Lịch sử liên kết</h3>${d.history.map(h=>`<div class="timeline-item"><strong>${esc(h.action)}</strong><small>${dt(h.at)} · ${esc(h.actor||'')}</small><p>${esc(h.reason)}</p></div>`).join('')||'<p class="small">Chưa có thay đổi liên kết được ghi nhận.</p>'}<p class="small">Ngày tạo: ${dt(c.created_at)} · Cập nhật: ${dt(c.updated_at)}</p></section></div>`);action(el,'[data-edit]',()=>editDirectoryContact(c,c.organization_id,render));action(el,'[data-unlink]',()=>unlinkDirectoryContact(c,render));return el;
};
