const lifecycleNames={customers:'khách hàng',opportunities:'cơ hội',quotes:'báo giá',tasks:'kế hoạch / công việc',knowledge:'nội dung bot',templates:'mẫu báo giá',products:'sản phẩm / dịch vụ','product-categories':'loại dịch vụ','work-templates':'mẫu công việc',teams:'nhóm làm việc',notes:'ghi chú',conversations:'hội thoại'};
function archiveRecord(kind,id,name,after=render){form('Lưu trữ '+name,[['reason','Lý do * — bỏ khỏi danh sách hoạt động, giữ lịch sử và có thể khôi phục','textarea']],async body=>{await api('/lifecycle/'+kind+'/'+encodeURIComponent(id)+'/archive',{body});toast('Đã lưu trữ; có thể khôi phục trong mục Đã lưu trữ.');after();});}
async function archivedRecords(kind){const rows=await api('/lifecycle/'+kind),dialog=$(`<dialog style="width:min(680px,94vw);padding:24px"><h2>${kind==='customers'?'Khách hàng đã xóa / lưu trữ':esc(lifecycleNames[kind])+' đã lưu trữ'}</h2><p class="small">Dữ liệu còn nguyên. Khôi phục để tiếp tục sử dụng trong phạm vi được giao.</p>${rows.map(r=>`<div class="balance"><div><strong>${esc(r.name.slice(0,180))}</strong><p class="small">${dt(r.at)} · ${esc(r.reason||'Đã lưu trữ')}</p></div><button data-restore-record="${esc(r.id)}">Khôi phục</button></div>`).join('')||'<p>Chưa có dữ liệu đã lưu trữ.</p>'}<div class="actions"><button id="close-archives">Đóng</button></div></dialog>`);document.body.append(dialog);dialog.showModal();dialog.onclose=()=>dialog.remove();action(dialog,'#close-archives',()=>dialog.close());action(dialog,'[data-restore-record]',async b=>{await api('/lifecycle/'+kind+'/'+encodeURIComponent(b.dataset.restoreRecord)+'/restore',{body:{}});dialog.close();toast('Đã khôi phục dữ liệu.');render();});}
function lifecycleBar(el,kind,list=[]){const bar=$(`<div class="actions lifecycle-bar"><span class="small">Quản lý ${esc(lifecycleNames[kind])}</span>${list.length?'<button data-archive-picker>Lưu trữ…</button>':''}<button data-archives>${kind==='customers'?'Đã xóa / Khôi phục':'Đã lưu trữ / Khôi phục'}</button></div>`);const heading=el.querySelector('.page-heading,.hero');if(heading)heading.after(bar);else el.prepend(bar);action(bar,'[data-archives]',()=>archivedRecords(kind));action(bar,'[data-archive-picker]',()=>form('Chọn '+lifecycleNames[kind]+' cần lưu trữ',[['record_id','Dữ liệu','select',list.map(r=>[r.code&&kind==='products'?r.code:r.id,r.name||r.title||r.code||r.body?.slice(0,100)||[r.customer_name,r.channel].filter(Boolean).join(' · ')])],['reason','Lý do * — giữ lịch sử, có thể khôi phục','textarea']],async body=>{await api('/lifecycle/'+kind+'/'+encodeURIComponent(body.record_id)+'/archive',{body});toast('Đã lưu trữ.');render();}));return bar;}
const lifecycleViewConfig=[['customers','customers','/customers',['sales','leader']],['pipeline','opportunities','/opportunities',['sales','leader']],['quotes','quotes','/quotes',['sales','leader']],['tasks','tasks','/tasks',['sales','leader']],['knowledge','knowledge','/knowledge',['leader','director']],['work-templates','work-templates','/work-templates',['leader']],['inbox','conversations','/conversations',['sales','leader']]];
for(const [view,kind,path,roles] of lifecycleViewConfig){const base=views[view];views[view]=async id=>{const el=await base(id);if(roles.includes(me.role))lifecycleBar(el,kind,kind==='customers'?[]:await api(path));return el;};}
const beforeLifecycleTemplates=views.templates;views.templates=async()=>{const el=await beforeLifecycleTemplates();if(me.role==='admin'){const [d,products,categories]=await Promise.all([api('/templates'),api('/products'),api('/product-categories')]);const section=$('<section class="card"><h3>Lưu trữ và khôi phục danh mục</h3><p class="small">Bỏ các mục không còn dùng khỏi danh sách. Báo giá đã lập giữ nguyên hạng mục và đơn giá.</p></section>');lifecycleBar(section,'templates',d.templates);lifecycleBar(section,'products',products);lifecycleBar(section,'product-categories',categories);el.append(section);}return el;};
async function recordLifecycle(el,kind,id,r,returnHash){
 if(!['sales','leader'].includes(me.role)&&kind!=='knowledge')return;
 const bar=$(`<div class="actions lifecycle-bar"><span class="small">${r.archived_at?(kind==='customers'?'Đã xóa / lưu trữ — có thể khôi phục':'Đã lưu trữ — chỉ xem lịch sử'):'Quản lý '+lifecycleNames[kind]}</span><button data-record-life>${r.archived_at?'Khôi phục':kind==='customers'?'Xóa khách hàng':'Lưu trữ'}</button><button data-record-archives>${kind==='customers'?'Đã xóa / Khôi phục':'Đã lưu trữ'}</button></div>`);
 if(r.archived_at)el.querySelectorAll('input,textarea,select,button').forEach(b=>b.disabled=true);
 el.prepend(bar);action(bar,'[data-record-archives]',()=>archivedRecords(kind));action(bar,'[data-record-life]',async()=>{if(r.archived_at){await api('/lifecycle/'+kind+'/'+id+'/restore',{body:{}});render();}else if(kind==='customers')deleteDirectoryCustomer({...r,id},()=>{go(returnHash);render();});else archiveRecord(kind,id,r.name||r.title||r.code,()=>{go(returnHash);render();});});
}
const beforeLifecycleCustomer=views.customer;views.customer=async id=>{const el=await beforeLifecycleCustomer(id),d=await api('/customers/'+id);await recordLifecycle(el,'customers',id,d.customer,'#/customers');if(!d.customer.archived_at){const notes=await api('/customers/'+id+'/notes'),bar=lifecycleBar(el,'notes',notes);if(notes.length){const edit=$('<button>Sửa ghi chú…</button>');bar.append(edit);edit.onclick=()=>form('Chọn ghi chú',[['note_id','Ghi chú','select',notes.map(n=>[n.id,n.body.slice(0,100)])]],async body=>{const note=notes.find(n=>String(n.id)===body.note_id);setTimeout(()=>form('Sửa ghi chú',[['body','Nội dung *','textarea',null,note.body]],async v=>{await api('/notes/'+note.id,{method:'PUT',body:v});render();}),0);});}}return el;};
const beforeLifecycleOpportunity=views.opportunity;views.opportunity=async id=>{await loadPipelineStages();const el=await beforeLifecycleOpportunity(id),d=await api('/opportunities/'+id);if(!d.opportunity.archived_at){const edit=$('<button>Sửa thông tin cơ hội</button>');el.querySelector('.page-heading .actions').append(edit);edit.onclick=()=>form('Sửa thông tin cơ hội',[['title','Tên cơ hội *','text',null,d.opportunity.title],['est_value','Giá trị dự kiến (VNĐ)','number',null,d.opportunity.est_value],['expected_close','Ngày dự kiến chốt','date',null,d.opportunity.expected_close||'']],async body=>{await api('/opportunities/'+id,{method:'PUT',body});render();});}await recordLifecycle(el,'opportunities',id,d.opportunity,'#/pipeline');return el;};
const beforeLifecycleQuote=views.quote;views.quote=async id=>{const el=await beforeLifecycleQuote(id),d=await api('/quotes/'+id);if(d.can_edit&&d.quote.status==='PENDING'&&!d.quote.archived_at){const b=$('<button>Rút khỏi chờ duyệt</button>');el.prepend(b);b.onclick=()=>form('Rút báo giá khỏi chờ duyệt',[['reason','Lý do *','textarea']],async body=>{await api('/quotes/'+id+'/withdraw',{body});render();});}await recordLifecycle(el,'quotes',id,d.quote,'#/quotes');return el;};
const beforeLifecycleArticle=views.article;views.article=async id=>{const el=await beforeLifecycleArticle(id),r=await api('/knowledge/'+id);if(['leader','director'].includes(me.role))await recordLifecycle(el,'knowledge',id,r,'#/knowledge');return el;};
const beforeLifecycleConversation=views.conversation;views.conversation=async id=>{const d=await api('/conversations/'+id),el=d.conversation.archived_at?$(`<div>${pageHeading('Hội thoại đã lưu trữ',d.customer.name)}<section class="card">${d.messages.map(m=>`<div class="balance"><span class="preserve">${esc(m.body)}</span><small>${dt(m.at)}</small></div>`).join('')}</section></div>`):await beforeLifecycleConversation(id);await recordLifecycle(el,'conversations',id,{...d.conversation,name:d.customer.name},'#/inbox');return el;};
const beforeLifecycleInbox=views.inbox;views.inbox=async()=>{const el=await beforeLifecycleInbox();if(['sales','leader'].includes(me.role)){const b=$('<button>+ Thêm hội thoại thử</button>');el.querySelector('.page-heading .actions').append(b);b.onclick=async()=>{const cs=await api('/customers');form('Tạo hội thoại thử trong CRM',[['customer_id','Khách hàng','select',cs.map(c=>[c.id,c.name])],['channel','Kênh thử','select',[['oa','Zalo OA (mô phỏng)'],['personal','Zalo cá nhân (mô phỏng)']]]],async body=>{const r=await api('/conversations',{body});go('#/conversation/'+r.id);});};}return el;};

views.users=async()=>{
 const [users,teams]=await Promise.all([api('/admin/users'),api('/admin/teams')]),activeTeams=teams.filter(t=>!t.archived_at);
 const el=$(`<div>${pageHeading('Người dùng & nhóm làm việc','Tạo tài khoản cho đội ngũ; khóa người nghỉ việc sau khi bàn giao dữ liệu.','<button class="major" id="add-user">+ Thêm người dùng</button>')}<section class="card"><div class="section-heading"><h3>Tài khoản người dùng</h3><select id="user-status" aria-label="Lọc trạng thái tài khoản"><option value="active">Đang hoạt động</option><option value="inactive">Đã khóa</option><option value="all">Tất cả</option></select></div><div style="overflow:auto"><table><thead><tr><th>Tài khoản</th><th>Họ tên</th><th>Vai trò / Nhóm</th><th>Chuyên môn</th><th>Thao tác</th></tr></thead><tbody></tbody></table></div><p class="small">Khóa tài khoản sẽ ngừng quyền đăng nhập, vẫn giữ tên người thực hiện trong lịch sử. Quyền xem khách theo vai trò và nhóm.</p></section><section class="card"><div class="section-heading"><h3>Nhóm làm việc</h3><button id="add-team">+ Thêm nhóm</button></div>${activeTeams.map(t=>`<div class="balance"><strong>${esc(t.name)}</strong><div class="actions"><button data-edit-team="${t.id}">Sửa</button><button data-archive-team="${t.id}">Lưu trữ</button></div></div>`).join('')}<button id="archived-teams">Nhóm đã lưu trữ / Khôi phục</button></section><a href="#/audit">Xem nhật ký hệ thống</a></div>`);
 const roleLabels={admin:'Admin công ty',subadmin:'Subadmin',leader:'Trưởng nhóm',sales:'Nhân viên sales',director:'Giám đốc'};
 const editUser=u=>form('Sửa thông tin tài khoản',[['name','Họ tên *','text',null,u.name],['expertise','Chuyên môn (cách nhau bằng dấu phẩy)','text',null,u.expertise],['password','Mật khẩu mới (bỏ trống để giữ)','password']],async body=>{await api('/admin/users/'+u.id,{method:'PUT',body:{...body,active:!!u.active}});render();});
 const fill=()=>{const filter=el.querySelector('#user-status').value;el.querySelector('tbody').innerHTML=users.filter(u=>filter==='all'||(filter==='active'?u.active:!u.active)).map(u=>`<tr><td>${esc(u.username)}<small style="display:block">${u.active?'Hoạt động':'Đã khóa'}</small></td><td>${esc(u.name)}</td><td>${u.role==='admin'&&u.admin_level==='subadmin'?'Subadmin':roleLabels[u.role]}<small style="display:block">${esc(teams.find(t=>t.id===u.team_id)?.name||'Chưa có nhóm')}</small></td><td>${esc(u.expertise||'')}</td><td><div class="actions"><button data-admin-level="${u.id}" ${u.role!=='admin'||isSubadmin()||u.id===me.id?'hidden':''}>Đổi cấp quản trị</button><button data-edit-user="${u.id}" ${isSubadmin()&&u.role==='admin'?'disabled':''}>Sửa</button><button data-user-status="${u.id}" ${u.id===me.id||isSubadmin()&&u.role==='admin'?'disabled':''}>${u.active?'Khóa / bàn giao':'Kích hoạt lại'}</button></div></td></tr>`).join('');action(el,'[data-admin-level]',b=>{const u=users.find(u=>u.id===Number(b.dataset.adminLevel));form('Đổi cấp quản trị — '+u.name,[['admin_level','Cấp quản trị','select',[['admin','Admin công ty'],['subadmin','Subadmin']],u.admin_level||'admin']],async body=>{await api('/admin/users/'+u.id+'/admin-level',{body});render();});});action(el,'[data-edit-user]',b=>editUser(users.find(u=>u.id===Number(b.dataset.editUser))));action(el,'[data-user-status]',async b=>{const u=users.find(u=>u.id===Number(b.dataset.userStatus));if(!u.active){await api('/admin/users/'+u.id+'/status',{body:{active:true}});render();return;}form('Khóa tài khoản '+u.username,[['transfer_to','Sales nhận bàn giao khách và việc (nếu có)','select',[['','Không có dữ liệu cần bàn giao'],...users.filter(v=>v.active&&v.role==='sales'&&v.team_id===u.team_id&&v.id!==u.id).map(v=>[v.id,v.name])]]],async body=>{await api('/admin/users/'+u.id+'/status',{body:{...body,active:false}});toast('Đã khóa tài khoản và xử lý bàn giao.');render();});});};fill();el.querySelector('#user-status').onchange=fill;
 action(el,'#add-user',()=>form('Thêm người dùng',[['username','Tên đăng nhập * (không dấu)','text'],['name','Họ tên *','text'],['role','Vai trò','select',Object.entries(roleLabels).filter(([k])=>!isSubadmin()||!['admin','subadmin'].includes(k)).map(([k,v])=>[k,v]),'sales'],['team_id','Nhóm làm việc','select',activeTeams.map(t=>[t.id,t.name])],['expertise','Chuyên môn','text'],['password','Mật khẩu ban đầu * (ít nhất 8 ký tự)','password']],async body=>{await api('/admin/users',{body});toast('Đã tạo tài khoản.');render();}));
 const editTeam=t=>form(t?'Sửa nhóm làm việc':'Thêm nhóm làm việc',[['name','Tên nhóm *','text',null,t?.name||'']],async body=>{await api('/admin/teams'+(t?'/'+t.id:''),{method:t?'PUT':'POST',body});render();});action(el,'#add-team',()=>editTeam());action(el,'[data-edit-team]',b=>editTeam(teams.find(t=>t.id===Number(b.dataset.editTeam))));action(el,'[data-archive-team]',b=>{const t=teams.find(t=>t.id===Number(b.dataset.archiveTeam));archiveRecord('teams',t.id,t.name);});action(el,'#archived-teams',()=>archivedRecords('teams'));return el;
};
async function loadPipelineStages(){const rows=await api('/pipeline-stages');STAGES.splice(0,STAGES.length,...rows.filter(s=>!s.archived_at).map(s=>s.name));return rows;}
const beforeDynamicPipeline=views.pipeline;views.pipeline=async id=>{await loadPipelineStages();return beforeDynamicPipeline(id);};
const beforeDynamicHome=views.home;views.home=async()=>{await loadPipelineStages();return beforeDynamicHome();};
const beforeLifecycleSettings=views.settings;views.settings=async()=>{const el=await beforeLifecycleSettings();if(me.role!=='admin')return el;const rows=await loadPipelineStages(),section=$(`<section class="card"><div class="section-heading"><h3>Các bước bán hàng</h3><button id="add-stage">+ Thêm bước</button></div><p class="small">Thêm bước trung gian theo quy trình công ty. Mới, Thắng, Thua giữ nguyên ý nghĩa nghiệp vụ. Cần chuyển cơ hội đang dùng trước khi ngừng một bước.</p>${rows.map(s=>`<div class="balance"><span>${esc(s.name)} ${s.archived_at?'· Đã ngừng':''}</span>${s.protected?'<span class="small">Bước nghiệp vụ bắt buộc</span>':`<button data-stage-status="${s.id}">${s.archived_at?'Dùng lại':'Ngừng dùng'}</button>`}</div>`).join('')}</section>`);el.append(section);action(section,'#add-stage',()=>form('Thêm bước bán hàng',[['name','Tên bước *','text']],async body=>{await api('/pipeline-stages',{body});render();}));action(section,'[data-stage-status]',async b=>{const s=rows.find(s=>s.id===Number(b.dataset.stageStatus));await api('/pipeline-stages/'+s.id+'/status',{body:{active:!!s.archived_at}});render();});return el;};
