const root=document.getElementById('platform-root');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const usageLabels={internal:'Dùng nội bộ',trial:'Dùng thử',customer:'Khách thuê dịch vụ'};
let currentUser=null,companies=[],filters={search:'',states:[],usages:[]},notice='';
const fold=v=>String(v).toLocaleLowerCase('vi').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d');
async function api(path,body){const r=await fetch('/api/platform'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.error||'Không thực hiện được thao tác.');return data;}
function formValues(form){return Object.fromEntries(new FormData(form));}
function bindForm(form,save){form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('[type=submit]'),error=form.querySelector('[role=alert]');error.textContent='';button.disabled=true;try{await save(formValues(form));}catch(e){error.textContent=e.message;}finally{button.disabled=false;}});}
function intro(){return '<div class="login-intro"><div class="eyebrow">IVITECH / SAAS</div><h1>Một nơi quản trị<br>các công ty trên nền tảng.</h1><p class="sub">Super Admin quản lý đơn vị sử dụng dịch vụ. Admin và subadmin của từng công ty làm việc trong không gian CRM riêng.</p><ul><li>Tạo công ty và tài khoản admin ban đầu.</li><li>Theo dõi công ty nội bộ, dùng thử và thuê dịch vụ.</li><li>Tạm dừng, mở lại và xem lịch sử quản trị.</li></ul><p class="hint">Tài khoản Super Admin không cấp quyền đọc khách hàng, báo giá hoặc hội thoại trong CRM của công ty thuê.</p></div>';}
async function renderLogin(){
 const status=await api('/status');
 if(!status.configured){
  root.innerHTML=`<div class="login-layout">${intro()}<section class="card"><span class="badge">Thiết lập lần đầu</span><h2>Khởi tạo Super Admin riêng</h2>${status.can_bootstrap?`<p class="sub">Chị đang đăng nhập tài khoản chủ nền tảng iViTech cũ. Xác nhận mật khẩu hiện tại và đặt tài khoản Super Admin mới.</p><form id="setup"><label>Mật khẩu admin iViTech hiện tại<input name="current_password" type="password" autocomplete="current-password" required></label><div class="two"><label>Tên đăng nhập Super Admin<input name="username" value="superadmin" autocomplete="off" required pattern="[a-zA-Z0-9._-]{3,60}" maxlength="60"></label><label>Họ tên người quản trị<input name="name" required maxlength="150" autocomplete="name"></label></div><label>Mật khẩu Super Admin mới<input name="password" type="password" autocomplete="new-password" minlength="12" maxlength="200" required></label><label>Nhập lại mật khẩu mới<input name="confirm_password" type="password" autocomplete="new-password" minlength="12" maxlength="200" required></label><p class="sub">Ít nhất 12 ký tự. Tài khoản admin công ty vẫn giữ nguyên; từ đây quản lý toàn hệ thống bằng tài khoản riêng này.</p><p class="error" role="alert"></p><button class="primary" type="submit">Khởi tạo và mở Quản trị nền tảng</button></form>`:`<p>Đăng nhập vào CRM bằng tài khoản admin iViTech đang giữ quyền chủ nền tảng, sau đó quay lại trang này để đặt tài khoản Super Admin riêng.</p><p><a href="/#/users">1. Đăng nhập admin iViTech →</a></p><button id="check-setup">2. Tôi đã đăng nhập — tiếp tục</button><p class="error" role="alert"></p>`}</section></div>`;
  if(status.can_bootstrap)bindForm(document.getElementById('setup'),async body=>{const r=await api('/bootstrap',body);currentUser=r.user;notice='Đã tạo tài khoản Super Admin riêng. Admin công ty không còn quyền quản lý nền tảng.';await dashboard();});
  else document.getElementById('check-setup').onclick=()=>renderLogin().catch(showError);return;
 }
 root.innerHTML=`<div class="login-layout">${intro()}<section class="card"><span class="badge">Super Admin</span><h2>Đăng nhập Quản trị nền tảng</h2><p class="sub">Dùng tài khoản Super Admin riêng, không dùng tài khoản admin công ty.</p><form id="platform-login"><label>Tên đăng nhập<input name="username" autocomplete="username" required maxlength="60"></label><label>Mật khẩu<input name="password" type="password" autocomplete="current-password" required maxlength="200"></label><p class="error" role="alert"></p><button class="primary" type="submit">Đăng nhập Super Admin</button></form><p><a href="/">Về màn hình đăng nhập CRM công ty →</a></p></section></div>`;
 bindForm(document.getElementById('platform-login'),async body=>{const r=await api('/login',body);currentUser=r.user;await dashboard();});
}
function showError(e){root.innerHTML=`<section class="card"><h1>Chưa mở được trang</h1><p class="error">${esc(e.message)}</p><a href="/platform">Thử lại</a></section>`;}
async function dashboard(){
 companies=await api('/companies');
 root.innerHTML=`<div class="hero"><div><div class="eyebrow">QUẢN TRỊ NỀN TẢNG</div><h1>Các công ty sử dụng dịch vụ</h1><p>Xin chào ${esc(currentUser.name)} · Super Admin. Quản lý công ty nội bộ và các đơn vị thuê Smart Omni CRM.</p></div><div class="actions"><button id="history">Nhật ký nền tảng</button><button id="logout">Đăng xuất Super Admin</button></div></div>${notice?`<p class="success" role="status">${esc(notice)}</p>`:''}<div class="stats"><div class="stat"><strong>${companies.length}</strong><span>CÔNG TY</span></div><div class="stat"><strong>${companies.filter(c=>c.state==='active').length}</strong><span>ĐANG HOẠT ĐỘNG</span></div><div class="stat"><strong>${companies.filter(c=>c.state==='paused').length}</strong><span>TẠM DỪNG</span></div></div><section class="card"><div class="section-head"><h2>Danh sách công ty</h2><button class="primary" id="new-company">+ Thêm công ty</button></div><div class="filters"><label>Tìm công ty<input type="search" id="search" placeholder="Tên hoặc mã công ty…" value="${esc(filters.search)}"></label><fieldset><legend>Trạng thái · chọn nhiều</legend>${[['active','Hoạt động'],['paused','Tạm dừng']].map(([k,v])=>`<label class="check"><input type="checkbox" data-state-filter="${k}" ${filters.states.includes(k)?'checked':''}>${v}</label>`).join('')}</fieldset><fieldset><legend>Mục đích · chọn nhiều</legend>${Object.entries(usageLabels).map(([k,v])=>`<label class="check"><input type="checkbox" data-usage-filter="${k}" ${filters.usages.includes(k)?'checked':''}>${v}</label>`).join('')}</fieldset><button id="clear-filters">Xóa lọc</button></div><p class="sub" id="count"></p><div class="table-wrap"><table><thead><tr><th>Công ty / Mã đăng nhập</th><th>Mục đích</th><th>Trạng thái</th><th>Ngày tạo</th><th>Thao tác</th></tr></thead><tbody id="company-rows"></tbody></table></div></section><p class="hint">Hiện quản lý công ty và trạng thái sử dụng. Bảng giá, gói thuê, thanh toán và gia hạn tự động sẽ bổ sung sau khi chốt chính sách kinh doanh.</p>`;
 document.getElementById('logout').onclick=async()=>{try{await api('/logout',{});currentUser=null;notice='';await renderLogin();}catch(e){showError(e);}};
 document.getElementById('new-company').onclick=createCompany;
 document.getElementById('history').onclick=()=>historyDialog().catch(showError);
 document.getElementById('search').oninput=e=>{filters.search=e.target.value;fill();};
 root.querySelectorAll('[data-state-filter],[data-usage-filter]').forEach(input=>input.onchange=()=>{filters.states=[...root.querySelectorAll('[data-state-filter]:checked')].map(n=>n.dataset.stateFilter);filters.usages=[...root.querySelectorAll('[data-usage-filter]:checked')].map(n=>n.dataset.usageFilter);fill();});
 document.getElementById('clear-filters').onclick=()=>{filters={search:'',states:[],usages:[]};document.getElementById('search').value='';root.querySelectorAll('.filters input[type=checkbox]').forEach(n=>n.checked=false);fill();};fill();
}
function fill(){const rows=companies.filter(c=>fold(c.name+' '+c.code).includes(fold(filters.search))&&(!filters.states.length||filters.states.includes(c.state))&&(!filters.usages.length||filters.usages.includes(c.usage)));document.getElementById('count').textContent=`${rows.length} / ${companies.length} công ty`;
 document.getElementById('company-rows').innerHTML=rows.map(c=>`<tr><td><strong>${esc(c.name)}</strong><small>${esc(c.code)}</small></td><td>${usageLabels[c.usage]}</td><td><span class="badge ${c.state==='paused'?'paused':''}">${c.state==='active'?'Hoạt động':'Tạm dừng'}</span></td><td>${new Date(c.created_at).toLocaleDateString('vi-VN')}</td><td>${c.code==='ivitech'?'<small>Công ty nội bộ iViTech</small>':`<button data-toggle="${esc(c.code)}">${c.state==='active'?'Tạm dừng':'Mở lại'}</button>`}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Không có công ty khớp bộ lọc.</td></tr>';
 root.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>stateCompany(companies.find(c=>c.code===b.dataset.toggle)));
}
function dialog(html){const d=document.createElement('dialog');d.innerHTML=html;document.body.append(d);d.onclose=()=>d.remove();d.querySelector('[data-cancel]')?.addEventListener('click',()=>d.close());d.showModal();return d;}
function createCompany(){const d=dialog(`<h2>Thêm công ty</h2><p class="sub">Tạo không gian dữ liệu riêng và một tài khoản admin ban đầu.</p><form><div class="two"><label>Mã công ty<input name="code" required pattern="[a-z0-9][a-z0-9-]{2,39}" maxlength="40" placeholder="vi-du-cong-ty"></label><label>Tên công ty<input name="name" required maxlength="150"></label></div><label>Mục đích sử dụng<select name="usage">${Object.entries(usageLabels).map(([k,v])=>`<option value="${k}" ${k==='trial'?'selected':''}>${v}</option>`).join('')}</select></label><h2>Admin của công ty mới</h2><div class="two"><label>Tên đăng nhập admin<input name="username" required pattern="[a-zA-Z0-9._-]{3,60}" maxlength="60"></label><label>Họ tên admin<input name="admin_name" required maxlength="150"></label></div><label>Mật khẩu admin ban đầu<input name="password" type="password" required minlength="8" maxlength="200" autocomplete="new-password"></label><p class="sub">Công ty mới không có dữ liệu khách hàng hoặc tài khoản mẫu của iViTech.</p><p class="error" role="alert"></p><div class="actions"><button class="primary" type="submit">Tạo công ty</button><button type="button" data-cancel>Hủy</button></div></form>`);bindForm(d.querySelector('form'),async body=>{const c=await api('/companies',body);notice=`Đã tạo ${c.name}. Đăng nhập CRM bằng mã công ty ${c.code} và tài khoản admin vừa đặt.`;d.close();await dashboard();});}
function stateCompany(c){const state=c.state==='active'?'paused':'active',d=dialog(`<h2>${state==='paused'?'Tạm dừng':'Mở lại'} ${esc(c.name)}</h2><p>${state==='paused'?'Ngừng truy cập công ty và thu hồi các phiên đăng nhập. Dữ liệu được giữ nguyên. Yêu cầu đã chuyển đến nhà cung cấp trước đó không thể thu hồi.':'Công ty hoạt động trở lại. Người dùng cần đăng nhập lại.'}</p><form><p class="error" role="alert"></p><div class="actions"><button class="primary" type="submit">Xác nhận ${state==='paused'?'tạm dừng':'mở lại'}</button><button type="button" data-cancel>Hủy</button></div></form>`);bindForm(d.querySelector('form'),async()=>{await api('/companies/'+c.code+'/state',{state});notice=`Đã ${state==='paused'?'tạm dừng':'mở lại'} ${c.name}.`;d.close();await dashboard();});}
async function historyDialog(){const rows=await api('/history'),labels={create:'Tạo công ty',active:'Mở lại công ty',paused:'Tạm dừng công ty',bootstrap_superadmin:'Khởi tạo Super Admin riêng',platform_login:'Đăng nhập Super Admin'};dialog(`<h2>Nhật ký nền tảng</h2><p class="sub">200 hoạt động gần nhất. Hoạt động trước khi tách Super Admin giữ mã người thực hiện cũ.</p>${rows.map(r=>`<p><strong>${esc(labels[r.action]||r.action)}</strong>${r.company?' · '+esc(r.company):''}<br><small>${new Date(r.at).toLocaleString('vi-VN')} · Mã người thực hiện ${r.actor??'—'}</small></p>`).join('')||'<p>Chưa có hoạt động.</p>'}<button data-cancel>Đóng</button>`);}
async function start(){try{currentUser=await api('/me');}catch{currentUser=null;}if(currentUser)await dashboard();else await renderLogin();}
start().catch(showError);
