const progressStyles=document.createElement('link');progressStyles.rel='stylesheet';progressStyles.href='/progress.css';document.head.append(progressStyles);
navItems.splice(3,0,['progress','Tiến trình khách hàng','calendar',0]);
Object.assign(statusText,{IN_PROGRESS:'Đang thực hiện',BLOCKED:'Đang vướng mắc'});
const progressPanels=new Map();
const workStates=[['OPEN','Chưa bắt đầu'],['IN_PROGRESS','Đang thực hiện'],['BLOCKED','Đang vướng mắc'],['COMPLETED','Hoàn thành']];
const workStateLabel=s=>workStates.find(x=>x[0]===s)?.[1]||s;
const workTone=s=>statusTone(s==='OPEN'?'TODO':s);
const workLocal=v=>v?new Date(Date.parse(v)+7*3600000).toISOString().slice(0,16):'';
const workUTC=v=>v?new Date(v+':00+07:00').toISOString():null;
function workStats(tasks){const active=tasks.filter(t=>!t.archived_at),leaves=active.filter(t=>!active.some(c=>c.parent_id===t.id)),done=leaves.filter(t=>t.status==='COMPLETED').length;return {total:leaves.length,done,pct:leaves.length?Math.round(done*100/leaves.length):0,state:leaves.length&&done===leaves.length?'COMPLETED':leaves.some(t=>t.status==='BLOCKED')?'BLOCKED':leaves.some(t=>t.status!=='OPEN')?'IN_PROGRESS':'OPEN'};}
views.progress=async focusId=>{
 const [projects,users,templates]=await Promise.all([api('/customer-progress'),api('/users'),api('/work-templates')]);let filter='all';
 const el=$(`<div>${pageHeading('Tiến trình khách hàng','Theo dõi đầu việc, công việc con và kết quả triển khai cho từng khách.',me.role==='leader'?'<button id="templates">Mẫu công việc</button>':'')}<div class="role-summary">Tiến độ = số việc cuối cùng đã hoàn thành / tổng số việc cuối cùng. Việc cha có công việc con không được đếm thêm. Công việc dùng chung với hồ sơ khách và lịch tiếp xúc.</div><div class="status-legend" aria-label="Chú thích màu trạng thái"><span>Trạng thái:</span>${workStates.map(([state,label])=>`<span class="tag ${workTone(state)}">${label}</span>`).join('')}</div><div class="progress-tools"><input type="search" id="progress-search" aria-label="Tìm khách trong tiến trình" placeholder="Tên khách, nền tảng, dịch vụ…"><select id="progress-filter" aria-label="Lọc tiến trình">${options([['all','Tất cả khách'],['OPEN','Chưa bắt đầu'],['IN_PROGRESS','Đang thực hiện'],['BLOCKED','Đang vướng mắc'],['COMPLETED','Hoàn thành']],filter)}</select></div><div id="projects"></div></div>`);
 const peopleFor=p=>me.role==='leader'?[['','Chưa giao · nhóm phụ trách'],...users.filter(u=>u.role==='leader'||u.id===p.customer.owner_id).map(u=>[u.id,u.name])]:[[me.id,me.name]];
 function editTask(p,t=null,parent=null){const fields=[['title','Tên đầu việc *','text',null,t?.title||''],['assignee_id','Người phụ trách','select',peopleFor(p),t?.assignee_id??(parent?p.tasks.find(x=>x.id===parent)?.assignee_id:p.customer.owner_id)??''],['started_at','Bắt đầu (giờ Việt Nam)','datetime-local',null,workLocal(t?.started_at)],['due_at','Hạn hoàn thành (giờ Việt Nam)','datetime-local',null,workLocal(t?.due_at)],['priority','Mức ưu tiên','select',[['Bình thường','Bình thường'],['Cao','Cao']],t?.priority||'Bình thường'],['note','Nội dung / kết quả cần đạt','textarea',null,t?.note||'']];form(t?'Sửa đầu việc':parent?'Thêm công việc con':'Thêm đầu việc',fields,async body=>{body.started_at=workUTC(body.started_at);body.due_at=workUTC(body.due_at);if(parent)body.parent_id=parent;await api(t?'/work-items/'+t.id:`/customers/${p.customer.id}/work-items`,{method:t?'PUT':'POST',body});go('#/progress/'+p.customer.id);render();});}
 function taskHTML(t,p,depth=0){const children=p.tasks.filter(c=>c.parent_id===t.id&&!c.archived_at),history=p.updates.filter(h=>h.task_id===t.id);return `<div class="work-row" data-task="${t.id}"><div class="work-head"><span class="work-dot ${t.status}"></span><div class="work-info"><strong>${esc(t.title)}</strong><small>Ngày tạo: ${esc(taskCreatedText(t.created_at))}</small><small>${t.started_at||t.due_at?`Thời gian: ${t.started_at?dueText(t.started_at):'Chưa đặt'} → ${t.due_at?dueText(t.due_at):'Chưa đặt'} · `:''}${t.assignee_name?'Người phụ trách: '+esc(t.assignee_name):'Nhóm phụ trách · chưa giao cá nhân'}${t.priority==='Cao'?' · Ưu tiên cao':''}</small></div><div class="work-controls">${children.length?`<span class="tag ${workTone(t.status)}">${workStateLabel(t.status)} · theo việc con</span>`:`<select class="${workTone(t.status)}" data-status-task="${t.id}" aria-label="Trạng thái ${esc(t.title)}">${options(workStates,t.status)}</select>`}<button data-edit="${t.id}" title="Sửa đầu việc">Sửa</button><button data-archive="${t.id}" title="Lưu trữ, có thể khôi phục">Lưu trữ</button></div></div><details class="work-details" data-panel="task:${t.id}" ${progressPanels.get('task:'+t.id)?'open':''}><summary>Tiến độ xử lý · Công việc con (${children.length})</summary><div class="work-panel">${t.note?`<p class="preserve">${esc(t.note)}</p>`:''}<div class="actions"><button data-update="${t.id}">Ghi nhận tiến độ</button>${depth<5?`<button data-child="${t.id}">+ Công việc con</button>`:''}</div>${children.length?`<div class="work-children">${children.map(c=>taskHTML(c,p,depth+1)).join('')}</div>`:'<p class="work-muted">Chưa có công việc con.</p>'}<div class="work-history">${history.map(h=>`<p>${esc(taskHistoryText(h.body))}<br><small>${esc(h.user_name||'Hệ thống')} · ${dt(h.at)}</small></p>`).join('')||'<p>Chưa có cập nhật.</p>'}</div></div></details></div>`;}
 function fill(){const term=el.querySelector('#progress-search').value.toLocaleLowerCase('vi');const visible=projects.filter(p=>(!focusId||String(p.customer.id)===String(focusId))&&(filter==='all'||workStats(p.tasks).state===filter)&&[p.customer.name,p.platform,...p.services].join(' ').toLocaleLowerCase('vi').includes(term));const box=el.querySelector('#projects');box.innerHTML=visible.map((p,i)=>{const stats=workStats(p.tasks),roots=p.tasks.filter(t=>!t.parent_id&&!t.archived_at),archived=p.tasks.filter(t=>t.archived_at&&!p.tasks.some(parent=>parent.id===t.parent_id&&parent.archived_at));return `<details class="customer-project" data-customer="${p.customer.id}" data-panel="customer:${p.customer.id}" ${(progressPanels.has('customer:'+p.customer.id)?progressPanels.get('customer:'+p.customer.id):i===0||focusId)?'open':''}><summary><span class="work-muted">#${i+1}</span><div class="project-name"><strong>${esc(p.customer.name)}</strong> <span class="tag ${workTone(stats.state)}">${workStateLabel(stats.state)}</span> ${p.platform?`<span class="tag quiet">${esc(p.platform)}</span>`:''}<small>${esc(p.address||'Chưa bổ sung địa chỉ triển khai')} · ${roots.length} đầu việc · ${stats.done}/${stats.total} việc cuối đã xong</small></div><span class="progress-ring" style="--pct:${stats.pct}" aria-label="Hoàn thành ${stats.pct}%"><span>${stats.pct}%</span></span><span>⌄</span></summary><div class="project-body"><div class="project-section-title"><h3>Thông tin đơn vị / khách hàng</h3><button data-info="${p.customer.id}">Sửa thông tin</button></div><div class="project-meta"><small class="work-muted">Nền tảng</small><br>${esc(p.platform||'Chưa chọn nền tảng')}<br><a href="#/customer/${p.customer.id}">Mở hồ sơ khách →</a></div><div class="project-section-title"><h3>Dịch vụ đăng ký</h3><button data-info="${p.customer.id}">+ Thêm dịch vụ</button></div><div class="services-list">${p.services.map(s=>`<span class="service-pill">${esc(s)}</span>`).join('')||'<span class="work-muted">Chưa ghi nhận dịch vụ.</span>'}</div><div class="project-section-title"><h3>Tiến độ công việc (${roots.length})</h3><div><button data-template="${p.customer.id}">Áp dụng mẫu</button><button data-new="${p.customer.id}">+ Thêm việc</button></div></div>${roots.map(t=>taskHTML(t,p)).join('')||'<div class="progress-empty">Chưa có đầu việc. Chọn Áp dụng mẫu hoặc Thêm việc để bắt đầu.</div>'}${archived.length?`<details class="project-archived"><summary>Việc đã lưu trữ (${archived.length})</summary>${archived.map(t=>`<div class="template-row"><span>${esc(t.title)}</span><button data-restore="${t.id}">Khôi phục</button></div>`).join('')}</details>`:''}</div></details>`;}).join('')||'<div class="progress-empty">Không có khách phù hợp.</div>';
  box.querySelectorAll('[data-panel]').forEach(panel=>panel.addEventListener('toggle',()=>progressPanels.set(panel.dataset.panel,panel.open)));
  const findProject=b=>projects.find(p=>String(p.customer.id)===b.closest('[data-customer]').dataset.customer),findTask=(p,id)=>p.tasks.find(t=>String(t.id)===String(id));
  action(box,'[data-info]',b=>{const p=findProject(b);form('Thông tin triển khai của khách',[['platform','Nền tảng / hình thức triển khai','text',null,p.platform],['address','Địa chỉ triển khai','text',null,p.address],['services','Dịch vụ đăng ký (mỗi dòng một dịch vụ)','textarea',null,p.services.join('\n')]],async body=>{body.services=body.services.split('\n').map(s=>s.trim()).filter(Boolean);await api(`/customers/${p.customer.id}/delivery`,{method:'PUT',body});render();});});
  action(box,'[data-new]',b=>editTask(findProject(b)));action(box,'[data-edit]',b=>{const p=findProject(b);editTask(p,findTask(p,b.dataset.edit));});action(box,'[data-child]',b=>editTask(findProject(b),null,Number(b.dataset.child)));
  box.querySelectorAll('[data-status-task]').forEach(select=>select.onchange=async()=>{select.disabled=true;try{await api('/work-items/'+select.dataset.statusTask+'/status',{body:{status:select.value}});render();}catch(e){toast(e.message);select.disabled=false;}});
  action(box,'[data-update]',b=>form('Ghi nhận tiến độ xử lý',[['body','Kết quả / vướng mắc / bước tiếp theo *','textarea']],async body=>{await api('/work-items/'+b.dataset.update+'/updates',{body});render();}));
  action(box,'[data-archive]',b=>form('Lưu trữ đầu việc và các việc con',[['reason','Lý do lưu trữ *','textarea']],async body=>{await api('/work-items/'+b.dataset.archive+'/archive',{body});render();}));action(box,'[data-restore]',async b=>{await api('/work-items/'+b.dataset.restore+'/restore',{body:{}});render();});
  action(box,'[data-template]',b=>{const p=findProject(b);if(!templates.length){toast('Trưởng nhóm cần tạo mẫu công việc trước.');return;}form('Áp dụng mẫu vào khách hàng',[['template_id','Mẫu công việc','select',templates.map(t=>[t.id,t.name])],['assignee_id','Người phụ trách mặc định','select',peopleFor(p),p.customer.owner_id||'']],async body=>{body.request_key=crypto.randomUUID();const r=await api(`/customers/${p.customer.id}/apply-work-template`,{body});toast('Đã thêm '+r.count+' đầu việc.');render();});});
 }
 fill();el.querySelector('#progress-search').oninput=fill;el.querySelector('#progress-filter').onchange=e=>{filter=e.target.value;fill();};action(el,'#templates',()=>go('#/work-templates'));if(focusId){const b=$('<button>Xem tất cả khách</button>');b.onclick=()=>go('#/progress');el.querySelector('.progress-tools').append(b);}return el;
};
views['work-templates']=async()=>{
 if(me.role!=='leader')throw Error('Trưởng nhóm quản lý mẫu công việc.');const list=await api('/work-templates');const el=$(`<div>${pageHeading('Mẫu công việc','Áp dụng mẫu để tạo tiến trình riêng cho từng khách. Sửa mẫu không thay đổi các việc đã tạo.','<button id="new-template">Tạo mẫu mới</button>')}<section class="card">${list.map(t=>`<div class="template-row"><div><strong>${esc(t.name)}</strong><p class="small">${t.items.length} đầu việc chính</p></div><button data-template-edit="${t.id}">Sửa mẫu</button></div>`).join('')}</section><a href="#/progress">← Tiến trình khách hàng</a></div>`);
 const flatten=(items,depth=0)=>items.map(i=>'  '.repeat(depth)+i.title+(i.children?.length?'\n'+flatten(i.children,depth+1):'')).join('\n');
 const parse=value=>{const root=[],stack=[root];let previous=0;for(const line of value.split('\n').filter(x=>x.trim())){const spaces=line.length-line.trimStart().length;if(spaces%2||spaces/2>previous+1)throw Error('Mỗi cấp con thụt 2 dấu cách, không bỏ qua cấp.');const depth=spaces/2;if(!stack[depth])throw Error('Cần có việc cha trước việc con.');const item={title:line.trim(),children:[]};stack[depth].push(item);stack[depth+1]=item.children;stack.length=depth+2;previous=depth;}return root;};
 const edit=t=>form(t?'Sửa mẫu công việc':'Tạo mẫu công việc',[['name','Tên mẫu *','text',null,t?.name||''],['outline','Các đầu việc: mỗi dòng một việc; việc con thụt 2 dấu cách','textarea',null,flatten(t?.items||[])]],async body=>{await api('/work-templates'+(t?'/'+t.id:''),{method:t?'PUT':'POST',body:{name:body.name,items:parse(body.outline)}});render();});action(el,'#new-template',()=>edit());action(el,'[data-template-edit]',b=>edit(list.find(t=>String(t.id)===b.dataset.templateEdit)));return el;
};
const priorCustomer=views.customer;views.customer=async id=>{const el=await priorCustomer(id);const a=$(`<a href="#/progress/${id}" class="tag ok">Xem tiến trình công việc →</a>`);el.querySelector('.page-heading .actions').append(a);return el;};
