// Real browser checks against a disposable database, never app/crm.db.
const {spawn}=require('node:child_process');
const {mkdirSync,rmSync,writeFileSync}=require('node:fs');
const {join}=require('node:path');
const assert=require('node:assert/strict');
const playwright=require(process.env.PLAYWRIGHT_PATH||'C:/Users/Nguyet/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const OUT=join(__dirname,'test-output');mkdirSync(OUT,{recursive:true});
const DB=join(OUT,`browser-${Date.now()}.db`),base='http://127.0.0.1:4002';
const checks=[],errors=[];let child,browser,page;
const done=s=>{checks.push(s);console.log(' ✓ '+s);};
async function ready(){child=spawn(process.execPath,[join(__dirname,'server.js')],{env:{...process.env,CRM_DB:DB,PORT:'4002'},stdio:['ignore','pipe','pipe']});let err='';child.stderr.on('data',x=>err+=x);await new Promise((ok,fail)=>{const t=setTimeout(()=>fail(Error('Server timeout '+err)),15000);child.once('error',fail);child.once('exit',c=>fail(Error('Server exited '+c+' '+err)));child.stdout.once('data',()=>{clearTimeout(t);ok();});});}
async function settled(){await page.waitForFunction(()=>document.querySelector('#main')&&!document.querySelector('#main').textContent.includes('Đang tải…'));assert.equal(await page.getByRole('heading',{name:'Không mở được',exact:true}).count(),0,await page.locator('body').innerText());}
async function visit(hash){await page.goto(base+'/'+hash);await settled();}
async function login(name){if(await page.locator('#out').count()){await page.locator('#out').click();await page.locator('#u').waitFor();}else await page.goto(base);await page.locator('#u').click();await page.locator('#u').press('ControlOrMeta+a');await page.locator('#u').pressSequentially(name);assert.equal(await page.locator('#u').inputValue(),name);await page.locator('#p').click();await page.locator('#p').press('ControlOrMeta+a');await page.locator('#p').pressSequentially('123456');await page.locator('#go').click();await settled();}
async function clickSave(){await page.locator('dialog button[type=submit]').click();await page.locator('dialog').waitFor({state:'detached'});await settled();}
async function json(path){const r=await page.request.get(base+'/api'+path);assert.equal(r.status(),200);return r.json();}
(async()=>{try{
 await ready();browser=await playwright.chromium.launch({channel:'msedge',headless:true});
 const ctx=await browser.newContext({viewport:{width:1440,height:980},colorScheme:'light',locale:'vi-VN'});page=await ctx.newPage();
 page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>errors.push(r.url()+': '+r.failure()?.errorText));
 await login('admin');await visit('#/settings');await page.locator('#example').click();await page.locator('#save').click();await page.getByRole('status').filter({hasText:'Đã lưu cấu hình'}).waitFor();
 await visit('#/templates');await page.locator('#brand-name').fill('iViTech - Kiểm thử giao diện');await page.locator('#brand').click();await page.getByRole('status').filter({hasText:'Đã lưu nhận diện'}).waitFor();
 await visit('#/users');assert.equal(await page.locator('[data-user]').count(),5);await visit('#/audit');await visit('#/guide');
 assert.equal(await page.locator('nav a[href="#/customers"]').count(),0);done('Admin lưu ngưỡng, nhận diện và mở tài khoản/nhật ký; menu đúng vai trò');
 await login('hoa');await visit('#/customers');await page.locator('#new').click();await page.locator('dialog [name=name]').fill('Khách kiểm thử giao diện');await page.locator('dialog [name=kind]').selectOption('person');await clickSave();
 await page.locator('#assign').click();await page.locator('dialog [name=user_id]').selectOption('1');await clickSave();await page.locator('#note').fill('Nhu cầu thử được lưu và kiểm tra lại.');await page.locator('#add-note').click();await page.locator('.timeline-item').filter({hasText:'Nhu cầu thử được lưu và kiểm tra lại.'}).waitFor();
 await page.screenshot({path:join(OUT,'customer-desktop.png'),fullPage:true});done('Trưởng nhóm tạo khách, phân công và lưu ghi chú');
 await visit('#/import');await page.locator('#file').setInputFiles({name:'test.csv',mimeType:'text/csv',buffer:Buffer.from('name,kind,phone,email,interest\nKhách CSV giao diện,person,,test@example.com,Đào tạo AI\n')});await page.getByText('Sẵn sàng',{exact:true}).waitFor();await page.locator('#confirm').check();await page.locator('#commit').click();await page.getByRole('link',{name:'Khách CSV giao diện',exact:true}).waitFor();done('CSV xem trước, xác nhận và nhập từ trình duyệt');
 await visit('#/knowledge');await page.locator('#new').click();await page.locator('dialog [name=title]').fill('Thời hạn đào tạo kiểm thử');await page.locator('dialog [name=keywords]').fill('thời hạn,đào tạo');await page.locator('dialog [name=body]').fill('Dịch vụ đào tạo có thời hạn 12 tháng từ ngày kích hoạt.');await clickSave();const articleHash=new URL(page.url()).hash;await page.locator('#submit').click();await page.getByText('Chờ duyệt',{exact:true}).waitFor();
 await login('duc');await visit(articleHash);await page.locator('#approve').click();await page.getByText('Đã duyệt',{exact:true}).waitFor();await visit('#/knowledge');await page.locator('#ask').fill('Thời hạn đào tạo?');await page.locator('#preview').click();await page.locator('#answer').getByText('Dịch vụ đào tạo có thời hạn 12 tháng từ ngày kích hoạt.',{exact:true}).waitFor();done('Soạn nội dung, gửi đúng cấp duyệt và thử FAQ có nguồn');
 await login('lan');await visit('#/quotes');await page.locator('#new').click();await page.locator('dialog [name=customer_id]').selectOption('1');await page.locator('dialog [name=template_id]').selectOption('solution');await clickSave();const quoteHash=new URL(page.url()).hash;
 await page.locator('[data-code=G1]').check();await page.locator('[data-code=G3]').check();
 assert.equal(await page.locator('[data-total=first]').innerText(),'998.000.000 đ');
 await page.locator('#discount').fill('10');
 assert.equal(await page.locator('[data-total=net]').innerText(),'898.200.000 đ');
 assert.equal(await page.locator('[data-total=renewal]').innerText(),'778.000.000 đ');
 await page.locator('[data-code=GFULL]').check();assert.equal(await page.locator('[data-code]:checked').count(),1);
 assert.equal(await page.locator('[data-total=first]').innerText(),'1.629.000.000 đ');
 await page.locator('[data-code=G1]').check();assert.equal(await page.locator('[data-code]:checked').count(),1);
 await page.locator('[data-code=G1]').uncheck();assert.equal(await page.locator('[data-total=first]').innerText(),'0 đ');
 await page.locator('[data-code=G1]').check();await page.locator('#discount').fill('101');assert.equal(await page.locator('#save').isDisabled(),true);
 await page.locator('#discount').fill('10');await page.locator('#save').click();await page.getByRole('heading',{name:'Giá trị báo giá đã lưu',exact:true}).waitFor();
 let saved=await json(quoteHash.replace('#/quote/','/quotes/'));assert.equal(saved.net_first_year,449100000);assert.equal(saved.totals.renewal,349000000);
 await page.reload();await settled();assert.ok((await page.locator('#quote-totals').innerText()).includes('449.100.000 đ'));
 done('Giá đổi ngay theo gói/chiết khấu, không cộng trùng trọn bộ, lưu và tải lại khớp số tiền');
 await page.locator('#discount').fill('0');await page.locator('#submit').click();await page.getByText('Chờ duyệt',{exact:true}).waitFor();
 await login('hoa');await visit(quoteHash);await page.locator('#approve').click();await page.getByText('Đã duyệt',{exact:true}).waitFor();
 await login('lan');await visit(quoteHash);await page.locator('#send').click();await page.locator('dialog [name=confirm]').check();await clickSave();await page.getByText('Đã gửi thử',{exact:true}).waitFor();
 await page.getByRole('link',{name:'Xem bản in / lưu PDF →'}).click();await page.getByRole('heading',{name:'BẢNG BÁO GIÁ',exact:true}).waitFor();assert.ok((await page.locator('.doc').innerText()).includes('iViTech - Kiểm thử giao diện'));assert.equal(await page.locator('.draft-mark').count(),0);await page.screenshot({path:join(OUT,'quote-desktop.png'),fullPage:true});
 await page.pdf({path:join(OUT,'quote-print-test.pdf'),format:'A4',printBackground:true});done('Sales tạo báo giá, trưởng nhóm duyệt, gửi thử và xuất bản in PDF');
 await visit('#/pipeline');await page.locator('#new').click();await page.locator('dialog [name=title]').fill('Cơ hội thử quy trình thua');await page.locator('dialog [name=customer_id]').selectOption('1');await clickSave();await page.locator('[data-s="Thua"]').click();await page.locator('dialog [name=reason]').fill('Khách chưa đủ ngân sách');await clickSave();await page.locator('[data-s="Đàm phán"]').click();await page.locator('dialog [name=reason]').fill('Khách xác nhận ngân sách mới');await clickSave();await page.getByText('Khách xác nhận ngân sách mới',{exact:true}).waitFor();assert.ok((await page.locator('main').innerText()).includes('Khách chưa đủ ngân sách'));await visit('#/pipeline');await page.screenshot({path:join(OUT,'pipeline-desktop.png'),fullPage:true});done('Cơ hội thua được mở lại có lý do và đủ lịch sử');
 await login('minh');const conv=(await json('/conversations')).find(c=>c.channel.includes('cá nhân'));assert.ok(conv,'Personal conversation fixture');await visit('#/conversation/'+conv.id);if(await page.getByRole('button',{name:'Chuyển lại cho bot',exact:true}).count()){await page.locator('#bot').click();await page.getByRole('button',{name:'Tiếp nhận · dừng bot',exact:true}).waitFor();}
 await page.locator('#test-message').click();await page.locator('dialog [name=outside_hours]').check();await clickSave();await page.locator('.msg.bot').filter({hasText:'12 tháng từ ngày kích hoạt'}).waitFor();assert.match(await page.locator('.msg.bot').last().innerText(),/giờ làm việc/);await page.locator('#bot').click();await page.getByRole('button',{name:'Chuyển lại cho bot',exact:true}).waitFor();let botCount=await page.locator('.msg.bot').count();let customerCount=await page.locator('.msg.customer').count();await page.locator('#test-message').click();await clickSave();await page.waitForFunction(n=>document.querySelectorAll('.msg.customer').length>n,customerCount);assert.equal(await page.locator('.msg.bot').count(),botCount);
 await page.locator('#reply').fill('Nhân viên đã tiếp nhận nhu cầu thử.');await page.locator('#send').click();await page.locator('.msg.agent').filter({hasText:'Nhân viên đã tiếp nhận nhu cầu thử.'}).waitFor();await page.screenshot({path:join(OUT,'inbox-desktop.png'),fullPage:true});done('Zalo cá nhân mô phỏng, FAQ ngoài giờ, dừng bot và gửi từ nhân viên');
 await visit('#/tasks');await visit('#/templates');await visit('#/settings');assert.equal(await page.locator('#save').count(),0);await visit('#/home');await page.screenshot({path:join(OUT,'home-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:join(OUT,'home-mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);done('Các màn hình còn lại mở được, sales không sửa cấu hình, giao diện 390px không tràn trang');
 assert.deepEqual(errors,[]);writeFileSync(join(OUT,'ui-results.json'),JSON.stringify({at:new Date().toISOString(),browser:'Microsoft Edge headless',checks,errors,mode:'disposable database',externalIntegrationsTested:false},null,2));console.log(checks.length+' nhóm kiểm tra trình duyệt đạt.');
}catch(e){if(page)await page.screenshot({path:join(OUT,'ui-failure.png'),fullPage:true}).catch(()=>{});console.error(e);process.exitCode=1;}finally{if(browser)await browser.close();if(child&&child.exitCode===null){child.kill();await new Promise(ok=>child.once('exit',ok));}for(const p of [DB,DB+'-wal',DB+'-shm'])rmSync(p,{force:true});}})();
